
import { AITool, Category } from './types';

export const CATEGORIES: Category[] = [
  'General LLM', 'AI Search', 'Image Gen', 'Video Gen', 'Audio & Music', 
  'Coding AI', 'Web Generation', 'PPT & Slides', 'Excel & Data', 'Document AI',
  'Task Agents', 'Productivity', 'Research', 'Marketing', 'Writing',
  'Design & UI', 'Education', 'Translation', 'Finance', 'Legal', 
  'Medical', 'Agent Frameworks', 'Character & Social', 'Developer Tools',
  'Gaming AI', 'Hardware AI', 'Enterprise AI'
];

export const INITIAL_TOOLS: AITool[] = [
  // --- GENERAL LLM (9 tools) ---
  { id: 'gpt-4o', name: 'GPT-4o', description: 'OpenAI 旗舰多模态模型，全球智能基准。', category: 'General LLM', tags: ['SOTA'], url: 'https://chat.openai.com', imageUrl: 'https://picsum.photos/seed/gpt4o/400/250', rating: 4.9, reviewCount: 1500, clickCount: 12000, favoritesCount: 4500, isVipEnabled: false, pricing: 'Freemium', reviews: [], status: 'approved', origin: 'Global' },
  { id: 'deepseek-v3', name: 'DeepSeek V3', description: '国产开源黑马，极致推理与极高性价比。', category: 'General LLM', tags: ['China'], url: 'https://chat.deepseek.com', imageUrl: 'https://picsum.photos/seed/ds3/400/250', rating: 4.98, reviewCount: 850, clickCount: 15000, favoritesCount: 9200, isVipEnabled: false, pricing: 'Free', reviews: [], status: 'approved', origin: 'China' },
  { id: 'claude-3-5', name: 'Claude 3.5 Sonnet', description: 'Anthropic 出品，代码与文案创作的神。', category: 'General LLM', tags: ['Reasoning'], url: 'https://claude.ai', imageUrl: 'https://picsum.photos/seed/claude/400/250', rating: 4.95, reviewCount: 1200, clickCount: 8500, favoritesCount: 3800, isVipEnabled: false, pricing: 'Freemium', reviews: [], status: 'approved', origin: 'Global' },
  { id: 'kimi', name: 'Kimi Chat', description: '月之暗面出品，超长上下文阅读专家。', category: 'General LLM', tags: ['LongText'], url: 'https://kimi.moonshot.cn', imageUrl: 'https://picsum.photos/seed/kimi/400/250', rating: 4.85, reviewCount: 650, clickCount: 7200, favoritesCount: 4100, isVipEnabled: false, pricing: 'Freemium', reviews: [], status: 'approved', origin: 'China' },
  { id: 'gemini-1-5', name: 'Gemini 1.5 Pro', description: 'Google 百万级上下文多模态大模型。', category: 'General LLM', tags: ['Google'], url: 'https://gemini.google.com', imageUrl: 'https://picsum.photos/seed/gemini/400/250', rating: 4.8, reviewCount: 520, clickCount: 6500, favoritesCount: 2800, isVipEnabled: false, pricing: 'Freemium', reviews: [], status: 'approved', origin: 'Global' },
  { id: 'qwen-2-5', name: '通义千问 2.5', description: '阿里巴巴最强开源模型，生态极其丰富。', category: 'General LLM', tags: ['Alibaba'], url: 'https://tongyi.aliyun.com', imageUrl: 'https://picsum.photos/seed/qwen/400/250', rating: 4.75, reviewCount: 420, clickCount: 5200, favoritesCount: 1900, isVipEnabled: false, pricing: 'Freemium', reviews: [], status: 'approved', origin: 'China' },
  { id: 'doubao', name: '豆包', description: '字节跳动出品，用户体验最流畅的 AI 助手。', category: 'General LLM', tags: ['ByteDance'], url: 'https://www.doubao.com', imageUrl: 'https://picsum.photos/seed/doubao/400/250', rating: 4.65, reviewCount: 1500, clickCount: 25000, favoritesCount: 12000, isVipEnabled: false, pricing: 'Free', reviews: [], status: 'approved', origin: 'China' },
  { id: 'mistral-large', name: 'Mistral Large', description: '欧洲最强 AI 力量，平衡效率与智能。', category: 'General LLM', tags: ['Efficiency'], url: 'https://mistral.ai', imageUrl: 'https://picsum.photos/seed/mistral/400/250', rating: 4.7, reviewCount: 180, clickCount: 2100, favoritesCount: 850, isVipEnabled: false, pricing: 'Freemium', reviews: [], status: 'approved', origin: 'Global' },
  { id: 'ernie-4', name: '文心一言 4.0', description: '百度旗舰大模型，中文知识深度覆盖。', category: 'General LLM', tags: ['Baidu'], url: 'https://yiyan.baidu.com', imageUrl: 'https://picsum.photos/seed/ernie/400/250', rating: 4.6, reviewCount: 950, clickCount: 12000, favoritesCount: 4500, isVipEnabled: false, pricing: 'Freemium', reviews: [], status: 'approved', origin: 'China' },

  // --- AI SEARCH (9 tools) ---
  { id: 'perplexity', name: 'Perplexity', description: '对话式搜索引擎，提供实时引用。', category: 'AI Search', tags: ['Leader'], url: 'https://perplexity.ai', imageUrl: 'https://picsum.photos/seed/pplx/400/250', rating: 4.92, reviewCount: 8500, clickCount: 120000, favoritesCount: 52000, isVipEnabled: false, pricing: 'Freemium', reviews: [], status: 'approved', origin: 'Global' },
  { id: 'metaso', name: '秘塔 AI 搜索', description: '国内顶尖 AI 搜索，无广告、深度聚合。', category: 'AI Search', tags: ['China'], url: 'https://metaso.cn', imageUrl: 'https://picsum.photos/seed/metaso/400/250', rating: 4.88, reviewCount: 4200, clickCount: 95000, favoritesCount: 31000, isVipEnabled: false, pricing: 'Free', reviews: [], status: 'approved', origin: 'China' },
  { id: 'felo', name: 'Felo Search', description: '跨语言搜索神器，用中文搜遍全球。', category: 'AI Search', tags: ['Translation'], url: 'https://felo.ai', imageUrl: 'https://picsum.photos/seed/felo/400/250', rating: 4.85, reviewCount: 1200, clickCount: 42000, favoritesCount: 15000, isVipEnabled: false, pricing: 'Free', reviews: [], status: 'approved', origin: 'Global' },
  { id: 'searchgpt', name: 'SearchGPT', description: 'OpenAI 官方搜索原型，极速响应。', category: 'AI Search', tags: ['OpenAI'], url: 'https://openai.com/searchgpt', imageUrl: 'https://picsum.photos/seed/sgpt/400/250', rating: 4.8, reviewCount: 500, clickCount: 85000, favoritesCount: 22000, isVipEnabled: false, pricing: 'Free', reviews: [], status: 'approved', origin: 'Global' },
  { id: '360-search', name: '360 AI 搜索', description: '老牌搜索厂商的 AI 进化。', category: 'AI Search', tags: ['China'], url: 'https://so.com', imageUrl: 'https://picsum.photos/seed/360/400/250', rating: 4.5, reviewCount: 3100, clickCount: 52000, favoritesCount: 12000, isVipEnabled: false, pricing: 'Free', reviews: [], status: 'approved', origin: 'China' },
  { id: 'devv', name: 'Devv.ai', description: '程序员专用 AI 搜索引擎。', category: 'AI Search', tags: ['Developer'], url: 'https://devv.ai', imageUrl: 'https://picsum.photos/seed/devv/400/250', rating: 4.95, reviewCount: 1500, clickCount: 45000, favoritesCount: 19000, isVipEnabled: false, pricing: 'Free', reviews: [], status: 'approved', origin: 'Global' },
  { id: 'genspark', name: 'Genspark', description: '生成式 AI 搜索，直接给出结构化答案。', category: 'AI Search', tags: ['Innovation'], url: 'https://genspark.ai', imageUrl: 'https://picsum.photos/seed/gensp/400/250', rating: 4.75, reviewCount: 420, clickCount: 15000, favoritesCount: 5400, isVipEnabled: false, pricing: 'Free', reviews: [], status: 'approved', origin: 'Global' },
  { id: 'you', name: 'You.com', description: '高度可定制的 AI 搜索工作台。', category: 'AI Search', tags: ['Custom'], url: 'https://you.com', imageUrl: 'https://picsum.photos/seed/you/400/250', rating: 4.7, reviewCount: 2100, clickCount: 38000, favoritesCount: 11000, isVipEnabled: false, pricing: 'Freemium', reviews: [], status: 'approved', origin: 'Global' },
  { id: 'andi', name: 'Andi Search', description: '简洁、私密的对话式搜索。', category: 'AI Search', tags: ['Minimalist'], url: 'https://andisearch.com', imageUrl: 'https://picsum.photos/seed/andi/400/250', rating: 4.6, reviewCount: 320, clickCount: 8200, favoritesCount: 2500, isVipEnabled: false, pricing: 'Free', reviews: [], status: 'approved', origin: 'Global' },

  // --- IMAGE GEN (9 tools) ---
  { id: 'midjourney', name: 'Midjourney', description: '顶级艺术感 AI 绘画，光影效果无敌。', category: 'Image Gen', tags: ['Art'], url: 'https://midjourney.com', imageUrl: 'https://picsum.photos/seed/mj/400/250', rating: 4.95, reviewCount: 52000, clickCount: 850000, favoritesCount: 410000, isVipEnabled: false, pricing: 'Paid', reviews: [], status: 'approved', origin: 'Global' },
  { id: 'flux', name: 'Flux.1', description: '新一代写实主义绘画巅峰。', category: 'Image Gen', tags: ['Realistic'], url: 'https://blackforestlabs.ai', imageUrl: 'https://picsum.photos/seed/flux/400/250', rating: 4.98, reviewCount: 8500, clickCount: 320000, favoritesCount: 150000, isVipEnabled: false, pricing: 'Free', reviews: [], status: 'approved', origin: 'Global' },
  { id: 'dalle3', name: 'DALL-E 3', description: '理解力极强，支持复杂文字指令。', category: 'Image Gen', tags: ['OpenAI'], url: 'https://openai.com/dall-e-3', imageUrl: 'https://picsum.photos/seed/dalle/400/250', rating: 4.85, reviewCount: 12000, clickCount: 450000, favoritesCount: 180000, isVipEnabled: false, pricing: 'Freemium', reviews: [], status: 'approved', origin: 'Global' },
  { id: 'jimeng', name: '即梦 (Dreamina)', description: '抖音旗下，国内最强的文生图工具。', category: 'Image Gen', tags: ['China'], url: 'https://jimeng.jianying.com', imageUrl: 'https://picsum.photos/seed/jimeng/400/250', rating: 4.9, reviewCount: 15000, clickCount: 520000, favoritesCount: 220000, isVipEnabled: false, pricing: 'Freemium', reviews: [], status: 'approved', origin: 'China' },
  { id: 'firefly', name: 'Adobe Firefly', description: '合规、商业友好的设计 AI。', category: 'Image Gen', tags: ['Design'], url: 'https://firefly.adobe.com', imageUrl: 'https://picsum.photos/seed/firefly/400/250', rating: 4.75, reviewCount: 5400, clickCount: 150000, favoritesCount: 62000, isVipEnabled: false, pricing: 'Freemium', reviews: [], status: 'approved', origin: 'Global' },
  { id: 'ideogram', name: 'Ideogram 2.0', description: '排版、平面设计文字生成首选。', category: 'Image Gen', tags: ['Graphic'], url: 'https://ideogram.ai', imageUrl: 'https://picsum.photos/seed/ideo/400/250', rating: 4.82, reviewCount: 3200, clickCount: 88000, favoritesCount: 35000, isVipEnabled: false, pricing: 'Freemium', reviews: [], status: 'approved', origin: 'Global' },
  { id: 'leonardo', name: 'Leonardo.ai', description: '功能极其全面的创作平台。', category: 'Image Gen', tags: ['Platform'], url: 'https://leonardo.ai', imageUrl: 'https://picsum.photos/seed/leo/400/250', rating: 4.8, reviewCount: 8500, clickCount: 180000, favoritesCount: 72000, isVipEnabled: false, pricing: 'Freemium', reviews: [], status: 'approved', origin: 'Global' },
  { id: 'huaban-ai', name: '花瓣美思', description: '国内设计师社区推出的 AI 辅助。', category: 'Image Gen', tags: ['China'], url: 'https://huaban.com', imageUrl: 'https://picsum.photos/seed/huaban/400/250', rating: 4.6, reviewCount: 1200, clickCount: 42000, favoritesCount: 15000, isVipEnabled: false, pricing: 'Freemium', reviews: [], status: 'approved', origin: 'China' },
  { id: 'stable-diffusion', name: 'Stable Diffusion', description: '开源绘图鼻祖，支持本地部署。', category: 'Image Gen', tags: ['OpenSource'], url: 'https://stability.ai', imageUrl: 'https://picsum.photos/seed/sd/400/250', rating: 4.9, reviewCount: 25000, clickCount: 1200000, favoritesCount: 580000, isVipEnabled: false, pricing: 'Free', reviews: [], status: 'approved', origin: 'Global' },

  // --- VIDEO GEN (9 tools) ---
  { id: 'kling', name: '可灵 (Kling)', description: '快手出品，国产 Sora，物理感极强。', category: 'Video Gen', tags: ['China'], url: 'https://klingai.kuaishou.com', imageUrl: 'https://picsum.photos/seed/kling/400/250', rating: 4.96, reviewCount: 12000, clickCount: 1500000, favoritesCount: 650000, isVipEnabled: false, pricing: 'Freemium', reviews: [], status: 'approved', origin: 'China' },
  { id: 'runway', name: 'Runway Gen-3', description: '视频 AI 的开创者，画质顶级。', category: 'Video Gen', tags: ['VFX'], url: 'https://runwayml.com', imageUrl: 'https://picsum.photos/seed/runway/400/250', rating: 4.9, reviewCount: 8500, clickCount: 950000, favoritesCount: 410000, isVipEnabled: false, pricing: 'Paid', reviews: [], status: 'approved', origin: 'Global' },
  { id: 'luma', name: 'Luma Dream Machine', description: '极速生成高动态、高写实视频。', category: 'Video Gen', tags: ['Fast'], url: 'https://lumalabs.ai', imageUrl: 'https://picsum.photos/seed/luma/400/250', rating: 4.88, reviewCount: 5400, clickCount: 820000, favoritesCount: 350000, isVipEnabled: false, pricing: 'Freemium', reviews: [], status: 'approved', origin: 'Global' },
  { id: 'vidu', name: 'Vidu', description: '清华团队背景，震撼的一键生片。', category: 'Video Gen', tags: ['China'], url: 'https://vidu.ai', imageUrl: 'https://picsum.photos/seed/vidu/400/250', rating: 4.8, reviewCount: 2100, clickCount: 420000, favoritesCount: 120000, isVipEnabled: false, pricing: 'Paid', reviews: [], status: 'approved', origin: 'China' },
  { id: 'pika', name: 'Pika Labs', description: '动画、风格化视频生成的王者。', category: 'Video Gen', tags: ['Animation'], url: 'https://pika.art', imageUrl: 'https://picsum.photos/seed/pika/400/250', rating: 4.75, reviewCount: 12000, clickCount: 680000, favoritesCount: 280000, isVipEnabled: false, pricing: 'Freemium', reviews: [], status: 'approved', origin: 'Global' },
  { id: 'heygen', name: 'HeyGen', description: '数字人、多语言配音视频首选。', category: 'Video Gen', tags: ['Avatar'], url: 'https://heygen.com', imageUrl: 'https://picsum.photos/seed/heygen/400/250', rating: 4.92, reviewCount: 15000, clickCount: 550000, favoritesCount: 320000, isVipEnabled: false, pricing: 'Paid', reviews: [], status: 'approved', origin: 'Global' },
  { id: 'sora', name: 'Sora', description: 'OpenAI 划时代作品（限内测）。', category: 'Video Gen', tags: ['OpenAI'], url: 'https://openai.com/sora', imageUrl: 'https://picsum.photos/seed/sora/400/250', rating: 4.99, reviewCount: 100, clickCount: 5000000, favoritesCount: 2500000, isVipEnabled: false, pricing: 'Paid', reviews: [], status: 'approved', origin: 'Global' },
  { id: 'hailuo', name: '海螺 AI 视频', description: 'MiniMax 旗下，极具写实感的视频生成。', category: 'Video Gen', tags: ['China'], url: 'https://hailuo.ai', imageUrl: 'https://picsum.photos/seed/hailuo/400/250', rating: 4.7, reviewCount: 3200, clickCount: 180000, favoritesCount: 65000, isVipEnabled: false, pricing: 'Free', reviews: [], status: 'approved', origin: 'China' },
  { id: 'synthesia', name: 'Synthesia', description: '企业级 AI 演示视频专家。', category: 'Video Gen', tags: ['Enterprise'], url: 'https://synthesia.io', imageUrl: 'https://picsum.photos/seed/synth/400/250', rating: 4.65, reviewCount: 4500, clickCount: 220000, favoritesCount: 82000, isVipEnabled: false, pricing: 'Paid', reviews: [], status: 'approved', origin: 'Global' },

  // --- AUDIO & MUSIC (9 tools) ---
  { id: 'suno', name: 'Suno AI', description: '一键生成包含人声的全长歌曲。', category: 'Audio & Music', tags: ['Music'], url: 'https://suno.com', imageUrl: 'https://picsum.photos/seed/suno/400/250', rating: 4.95, reviewCount: 25000, clickCount: 5000000, favoritesCount: 2100000, isVipEnabled: false, pricing: 'Freemium', reviews: [], status: 'approved', origin: 'Global' },
  { id: 'udio', name: 'Udio', description: '录音室级别的高保真音乐生成。', category: 'Audio & Music', tags: ['HiFi'], url: 'https://udio.com', imageUrl: 'https://picsum.photos/seed/udio/400/250', rating: 4.92, reviewCount: 8500, clickCount: 1500000, favoritesCount: 620000, isVipEnabled: false, pricing: 'Freemium', reviews: [], status: 'approved', origin: 'Global' },
  { id: 'elevenlabs', name: 'ElevenLabs', description: '全球最强的 AI 配音与声音克隆。', category: 'Audio & Music', tags: ['Voice'], url: 'https://elevenlabs.io', imageUrl: 'https://picsum.photos/seed/eleven/400/250', rating: 4.96, reviewCount: 12000, clickCount: 3500000, favoritesCount: 1500000, isVipEnabled: false, pricing: 'Freemium', reviews: [], status: 'approved', origin: 'Global' },
  { id: 'ace-studio', name: 'ACE Studio', description: '国产专业 AI 歌声合成，调教极其细腻。', category: 'Audio & Music', tags: ['China'], url: 'https://ace-studio.com', imageUrl: 'https://picsum.photos/seed/ace/400/250', rating: 4.88, reviewCount: 3200, clickCount: 210000, favoritesCount: 92000, isVipEnabled: false, pricing: 'Paid', reviews: [], status: 'approved', origin: 'China' },
  { id: 'tianyin', name: '网易天音', description: '网易云音乐出品，一键生成旋律。', category: 'Audio & Music', tags: ['China'], url: 'https://tianyin.music.163.com', imageUrl: 'https://picsum.photos/seed/tianyin/400/250', rating: 4.5, reviewCount: 5200, clickCount: 450000, favoritesCount: 140000, isVipEnabled: false, pricing: 'Freemium', reviews: [], status: 'approved', origin: 'China' },
  { id: 'stable-audio', name: 'Stable Audio', description: '长时长、高采样率音频生成。', category: 'Audio & Music', tags: ['Stability'], url: 'https://stableaudio.com', imageUrl: 'https://picsum.photos/seed/saudio/400/250', rating: 4.7, reviewCount: 1500, clickCount: 120000, favoritesCount: 52000, isVipEnabled: false, pricing: 'Freemium', reviews: [], status: 'approved', origin: 'Global' },
  { id: 'soundraw', name: 'Soundraw', description: '为博主设计的免版税 AI 乐库。', category: 'Audio & Music', tags: ['RoyaltyFree'], url: 'https://soundraw.io', imageUrl: 'https://picsum.photos/seed/sound/400/250', rating: 4.6, reviewCount: 2100, clickCount: 88000, favoritesCount: 31000, isVipEnabled: false, pricing: 'Paid', reviews: [], status: 'approved', origin: 'Global' },
  { id: 'voicify', name: 'Voicify', description: '目前最火的 AI 翻唱工具。', category: 'Audio & Music', tags: ['Cover'], url: 'https://voicify.ai', imageUrl: 'https://picsum.photos/seed/voicify/400/250', rating: 4.65, reviewCount: 8500, clickCount: 920000, favoritesCount: 450000, isVipEnabled: false, pricing: 'Paid', reviews: [], status: 'approved', origin: 'Global' },
  { id: 'musiclm', name: 'MusicLM (Google)', description: 'Google 的高保真音乐实验项目。', category: 'Audio & Music', tags: ['Google'], url: 'https://aitestkitchen.withgoogle.com', imageUrl: 'https://picsum.photos/seed/mlm/400/250', rating: 4.4, reviewCount: 500, clickCount: 35000, favoritesCount: 12000, isVipEnabled: false, pricing: 'Free', reviews: [], status: 'approved', origin: 'Global' },

  // --- CODING AI (9 tools) ---
  { id: 'cursor', name: 'Cursor', description: '全球首选的 AI Native 代码编辑器。', category: 'Coding AI', tags: ['IDE'], url: 'https://cursor.com', imageUrl: 'https://picsum.photos/seed/cursor/400/250', rating: 4.97, reviewCount: 15000, clickCount: 1200000, favoritesCount: 650000, isVipEnabled: false, pricing: 'Freemium', reviews: [], status: 'approved', origin: 'Global' },
  { id: 'github-copilot', name: 'GitHub Copilot', description: '最受开发者信任的编程伴侣。', category: 'Coding AI', tags: ['MS'], url: 'https://github.com/features/copilot', imageUrl: 'https://picsum.photos/seed/gh/400/250', rating: 4.9, reviewCount: 150000, clickCount: 5000000, favoritesCount: 2500000, isVipEnabled: false, pricing: 'Paid', reviews: [], status: 'approved', origin: 'Global' },
  { id: 'marscode', name: 'MarsCode', description: '字节跳动出品，极致流畅的编程辅助。', category: 'Coding AI', tags: ['China'], url: 'https://www.marscode.cn', imageUrl: 'https://picsum.photos/seed/mars/400/250', rating: 4.8, reviewCount: 8500, clickCount: 350000, favoritesCount: 110000, isVipEnabled: false, pricing: 'Free', reviews: [], status: 'approved', origin: 'China' },
  { id: 'comate', name: 'Baidu Comate', description: '百度推出的中文场景最强编程助手。', category: 'Coding AI', tags: ['China'], url: 'https://comate.baidu.com', imageUrl: 'https://picsum.photos/seed/comate/400/250', rating: 4.7, reviewCount: 12000, clickCount: 880000, favoritesCount: 210000, isVipEnabled: false, pricing: 'Freemium', reviews: [], status: 'approved', origin: 'China' },
  { id: 'codeium', name: 'Codeium', description: '全能且对个人完全免费的编程助手。', category: 'Coding AI', tags: ['Free'], url: 'https://codeium.com', imageUrl: 'https://picsum.photos/seed/codeium/400/250', rating: 4.85, reviewCount: 5200, clickCount: 520000, favoritesCount: 220000, isVipEnabled: false, pricing: 'Freemium', reviews: [], status: 'approved', origin: 'Global' },
  { id: 'tabnine', name: 'Tabnine', description: '老牌 AI 编程，强调隐私与本地模型。', category: 'Coding AI', tags: ['Privacy'], url: 'https://tabnine.com', imageUrl: 'https://picsum.photos/seed/tabnine/400/250', rating: 4.6, reviewCount: 21000, clickCount: 1200000, favoritesCount: 450000, isVipEnabled: false, pricing: 'Paid', reviews: [], status: 'approved', origin: 'Global' },
  { id: 'amazon-q', name: 'Amazon Q', description: 'AWS 官方出品，深度集成云资源。', category: 'Coding AI', tags: ['AWS'], url: 'https://aws.amazon.com/q', imageUrl: 'https://picsum.photos/seed/aws/400/250', rating: 4.5, reviewCount: 1500, clickCount: 310000, favoritesCount: 92000, isVipEnabled: false, pricing: 'Freemium', reviews: [], status: 'approved', origin: 'Global' },
  { id: 'replit', name: 'Replit Ghostwriter', description: '云端 IDE 无缝协作编程。', category: 'Coding AI', tags: ['Cloud'], url: 'https://replit.com', imageUrl: 'https://picsum.photos/seed/repl/400/250', rating: 4.75, reviewCount: 8500, clickCount: 650000, favoritesCount: 280000, isVipEnabled: false, pricing: 'Paid', reviews: [], status: 'approved', origin: 'Global' },
  { id: 'hw-codearts', name: 'Huawei CodeArts Snap', description: '华为云开发者助手，大中型政企首选。', category: 'Coding AI', tags: ['China'], url: 'https://www.huaweicloud.com', imageUrl: 'https://picsum.photos/seed/hw/400/250', rating: 4.4, reviewCount: 3100, clickCount: 110000, favoritesCount: 35000, isVipEnabled: false, pricing: 'Paid', reviews: [], status: 'approved', origin: 'China' },

  // --- PRODUCTIVITY (9 tools) ---
  { id: 'notion', name: 'Notion AI', description: '笔记、任务、知识库的智能大脑。', category: 'Productivity', tags: ['Knowledge'], url: 'https://notion.so', imageUrl: 'https://picsum.photos/seed/notion/400/250', rating: 4.9, reviewCount: 85000, clickCount: 5000000, favoritesCount: 2500000, isVipEnabled: false, pricing: 'Freemium', reviews: [], status: 'approved', origin: 'Global' },
  { id: 'otter', name: 'Otter.ai', description: '会议转录与自动摘要的首选。', category: 'Productivity', tags: ['Meeting'], url: 'https://otter.ai', imageUrl: 'https://picsum.photos/seed/otter/400/250', rating: 4.8, reviewCount: 12000, clickCount: 880000, favoritesCount: 320000, isVipEnabled: false, pricing: 'Freemium', reviews: [], status: 'approved', origin: 'Global' },
  { id: 'monica', name: 'Monica AI', description: '国产全能浏览器助手，覆盖所有工作流。', category: 'Productivity', tags: ['China'], url: 'https://monica.im', imageUrl: 'https://picsum.photos/seed/monica/400/250', rating: 4.88, reviewCount: 25000, clickCount: 1200000, favoritesCount: 540000, isVipEnabled: false, pricing: 'Freemium', reviews: [], status: 'approved', origin: 'China' },
  { id: 'fireflies', name: 'Fireflies.ai', description: '跨平台会议录制与数据挖掘。', category: 'Productivity', tags: ['Audio'], url: 'https://fireflies.ai', imageUrl: 'https://picsum.photos/seed/ff/400/250', rating: 4.75, reviewCount: 5200, clickCount: 250000, favoritesCount: 92000, isVipEnabled: false, pricing: 'Freemium', reviews: [], status: 'approved', origin: 'Global' },
  { id: 'readai', name: 'Read AI', description: '分析会议效率与团队情绪。', category: 'Productivity', tags: ['Insights'], url: 'https://read.ai', imageUrl: 'https://picsum.photos/seed/read/400/250', rating: 4.65, reviewCount: 1800, clickCount: 110000, favoritesCount: 42000, isVipEnabled: false, pricing: 'Freemium', reviews: [], status: 'approved', origin: 'Global' },
  { id: 'glean', name: 'Glean', description: '企业内部文档搜索与知识大脑。', category: 'Productivity', tags: ['Enterprise'], url: 'https://glean.com', imageUrl: 'https://picsum.photos/seed/glean/400/250', rating: 4.7, reviewCount: 500, clickCount: 45000, favoritesCount: 18000, isVipEnabled: false, pricing: 'Paid', reviews: [], status: 'approved', origin: 'Global' },
  { id: 'flowith', name: 'Flowith', description: '国产画布式 AI 工作流，极简高效。', category: 'Productivity', tags: ['China'], url: 'https://flowith.io', imageUrl: 'https://picsum.photos/seed/flow/400/250', rating: 4.82, reviewCount: 850, clickCount: 62000, favoritesCount: 28000, isVipEnabled: false, pricing: 'Freemium', reviews: [], status: 'approved', origin: 'China' },
  { id: 'taskade', name: 'Taskade AI', description: '一体化团队协作与 AI 智能体。', category: 'Productivity', tags: ['Team'], url: 'https://taskade.com', imageUrl: 'https://picsum.photos/seed/taska/400/250', rating: 4.78, reviewCount: 4200, clickCount: 150000, favoritesCount: 65000, isVipEnabled: false, pricing: 'Freemium', reviews: [], status: 'approved', origin: 'Global' },
  { id: 'mem', name: 'Mem.ai', description: '自动整理、自愈式的笔记系统。', category: 'Productivity', tags: ['SelfOrganizing'], url: 'https://mem.ai', imageUrl: 'https://picsum.photos/seed/mem/400/250', rating: 4.6, reviewCount: 1200, clickCount: 88000, favoritesCount: 31000, isVipEnabled: false, pricing: 'Paid', reviews: [], status: 'approved', origin: 'Global' },

  // --- RESEARCH (9 tools) ---
  { id: 'elicit', name: 'Elicit', description: '学术研究助理，自动提取论文核心。', category: 'Research', tags: ['Academic'], url: 'https://elicit.org', imageUrl: 'https://picsum.photos/seed/elic/400/250', rating: 4.9, reviewCount: 5200, clickCount: 350000, favoritesCount: 150000, isVipEnabled: false, pricing: 'Freemium', reviews: [], status: 'approved', origin: 'Global' },
  { id: 'consensus', name: 'Consensus', description: '只提供真实科学证据的 AI 搜索。', category: 'Research', tags: ['Evidence'], url: 'https://consensus.app', imageUrl: 'https://picsum.photos/seed/cons/400/250', rating: 4.85, reviewCount: 3200, clickCount: 220000, favoritesCount: 92000, isVipEnabled: false, pricing: 'Freemium', reviews: [], status: 'approved', origin: 'Global' },
  { id: 'aminer', name: 'AMiner', description: '清华团队打造，全球科研情报专家。', category: 'Research', tags: ['China'], url: 'https://www.aminer.cn', imageUrl: 'https://picsum.photos/seed/aminer/400/250', rating: 4.88, reviewCount: 15000, clickCount: 1200000, favoritesCount: 450000, isVipEnabled: false, pricing: 'Free', reviews: [], status: 'approved', origin: 'China' },
  { id: 'scispace', name: 'SciSpace', description: '论文阅读、改写与管理的端到端平台。', category: 'Research', tags: ['TypeSet'], url: 'https://typeset.io', imageUrl: 'https://picsum.photos/seed/scis/400/250', rating: 4.82, reviewCount: 6500, clickCount: 520000, favoritesCount: 210000, isVipEnabled: false, pricing: 'Freemium', reviews: [], status: 'approved', origin: 'Global' },
  { id: 'scite', name: 'scite.ai', description: '通过 AI 分析论文引用的背景。', category: 'Research', tags: ['Citations'], url: 'https://scite.ai', imageUrl: 'https://picsum.photos/seed/scite/400/250', rating: 4.75, reviewCount: 1200, clickCount: 110000, favoritesCount: 35000, isVipEnabled: false, pricing: 'Paid', reviews: [], status: 'approved', origin: 'Global' },
  { id: 'scholar-ai', name: 'ScholarAI', description: '搜索并分析全球学术数据库。', category: 'Research', tags: ['Plugin'], url: 'https://scholarai.io', imageUrl: 'https://picsum.photos/seed/sch/400/250', rating: 4.7, reviewCount: 850, clickCount: 85000, favoritesCount: 28000, isVipEnabled: false, pricing: 'Freemium', reviews: [], status: 'approved', origin: 'Global' },
  { id: 'semantic-scholar', name: 'Semantic Scholar', description: '艾伦研究所出品，免费 AI 学术引擎。', category: 'Research', tags: ['Free'], url: 'https://www.semanticscholar.org', imageUrl: 'https://picsum.photos/seed/sem/400/250', rating: 4.6, reviewCount: 52000, clickCount: 3500000, favoritesCount: 1200000, isVipEnabled: false, pricing: 'Free', reviews: [], status: 'approved', origin: 'Global' },
  { id: 'zotero-ai', name: 'Zotero AI Plugins', description: '通过社区插件增强文献管理。', category: 'Research', tags: ['Classic'], url: 'https://www.zotero.org', imageUrl: 'https://picsum.photos/seed/zot/400/250', rating: 4.5, reviewCount: 25000, clickCount: 1500000, favoritesCount: 850000, isVipEnabled: false, pricing: 'Free', reviews: [], status: 'approved', origin: 'Global' },
  { id: 'connected-papers', name: 'Connected Papers', description: '可视化论文图谱，发现领域关联。', category: 'Research', tags: ['Graph'], url: 'https://www.connectedpapers.com', imageUrl: 'https://picsum.photos/seed/conn/400/250', rating: 4.8, reviewCount: 4200, clickCount: 180000, favoritesCount: 75000, isVipEnabled: false, pricing: 'Freemium', reviews: [], status: 'approved', origin: 'Global' },

  // --- MARKETING (9 tools) ---
  { id: 'adcreative', name: 'AdCreative.ai', description: '一键生成高转化率社交广告素材。', category: 'Marketing', tags: ['Ads'], url: 'https://adcreative.ai', imageUrl: 'https://picsum.photos/seed/adcr/400/250', rating: 4.8, reviewCount: 1500, clickCount: 45000, favoritesCount: 18000, isVipEnabled: false, pricing: 'Paid', reviews: [], status: 'approved', origin: 'Global' },
  { id: 'mutiny', name: 'Mutiny', description: '基于 AI 的 B2B 网站个性化转换。', category: 'Marketing', tags: ['Conversion'], url: 'https://mutinyhq.com', imageUrl: 'https://picsum.photos/seed/mut/400/250', rating: 4.7, reviewCount: 320, clickCount: 12000, favoritesCount: 4500, isVipEnabled: false, pricing: 'Paid', reviews: [], status: 'approved', origin: 'Global' },
  { id: 'anyword', name: 'Anyword', description: '预测文案转化效果，智能优化。', category: 'Marketing', tags: ['Copy'], url: 'https://anyword.com', imageUrl: 'https://picsum.photos/seed/any/400/250', rating: 4.6, reviewCount: 1200, clickCount: 48000, favoritesCount: 15000, isVipEnabled: false, pricing: 'Paid', reviews: [], status: 'approved', origin: 'Global' },
  { id: 'marketmuse', name: 'MarketMuse', description: 'AI 驱动的内容规划与 SEO 优化。', category: 'Marketing', tags: ['SEO'], url: 'https://marketmuse.com', imageUrl: 'https://picsum.photos/seed/mm/400/250', rating: 4.75, reviewCount: 850, clickCount: 22000, favoritesCount: 7500, isVipEnabled: false, pricing: 'Paid', reviews: [], status: 'approved', origin: 'Global' },
  { id: 'smartly', name: 'Smartly.io', description: '全自动、跨渠道的社交广告投放。', category: 'Marketing', tags: ['Ads'], url: 'https://smartly.io', imageUrl: 'https://picsum.photos/seed/smart/400/250', rating: 4.5, reviewCount: 520, clickCount: 35000, favoritesCount: 12000, isVipEnabled: false, pricing: 'Paid', reviews: [], status: 'approved', origin: 'Global' },
  { id: 'volc-marketing', name: '火山营销 (火山引擎)', description: '字节跳动旗下企业智能营销平台。', category: 'Marketing', tags: ['China'], url: 'https://volcengine.com', imageUrl: 'https://picsum.photos/seed/volc/400/250', rating: 4.82, reviewCount: 3100, clickCount: 520000, favoritesCount: 190000, isVipEnabled: false, pricing: 'Paid', reviews: [], status: 'approved', origin: 'China' },
  { id: 'baidu-ads', name: '百度营销 AIGC', description: '基于文心的创意文案与海报生成。', category: 'Marketing', tags: ['China'], url: 'https://e.baidu.com', imageUrl: 'https://picsum.photos/seed/bdm/400/250', rating: 4.7, reviewCount: 8500, clickCount: 850000, favoritesCount: 220000, isVipEnabled: false, pricing: 'Paid', reviews: [], status: 'approved', origin: 'China' },
  { id: 'growingio', name: 'GrowingIO AI', description: '国产全渠道分析与增长引擎。', category: 'Marketing', tags: ['China'], url: 'https://growingio.com', imageUrl: 'https://picsum.photos/seed/gio/400/250', rating: 4.65, reviewCount: 1200, clickCount: 95000, favoritesCount: 32000, isVipEnabled: false, pricing: 'Paid', reviews: [], status: 'approved', origin: 'China' },
  { id: 'insider', name: 'Insider AI', description: '多渠道客户体验编排与转化。', category: 'Marketing', tags: ['Experience'], url: 'https://useinsider.com', imageUrl: 'https://picsum.photos/seed/ins/400/250', rating: 4.7, reviewCount: 420, clickCount: 15000, favoritesCount: 5200, isVipEnabled: false, pricing: 'Paid', reviews: [], status: 'approved', origin: 'Global' },

  // --- WRITING (9 tools) ---
  { id: 'quillbot', name: 'QuillBot', description: '全球首选的改写与润色神器。', category: 'Writing', tags: ['Paraphrasing'], url: 'https://quillbot.com', imageUrl: 'https://picsum.photos/seed/quill/400/250', rating: 4.9, reviewCount: 12000, clickCount: 250000, favoritesCount: 95000, isVipEnabled: false, pricing: 'Freemium', reviews: [], status: 'approved', origin: 'Global' },
  { id: 'wordtune', name: 'Wordtune', description: '实时调整语气与风格的改写助手。', category: 'Writing', tags: ['Tone'], url: 'https://wordtune.com', imageUrl: 'https://picsum.photos/seed/word/400/250', rating: 4.8, reviewCount: 5400, clickCount: 110000, favoritesCount: 42000, isVipEnabled: false, pricing: 'Freemium', reviews: [], status: 'approved', origin: 'Global' },
  { id: 'ginger', name: 'Ginger Software', description: '深度英文语法纠错与写作优化。', category: 'Writing', tags: ['Grammar'], url: 'https://gingersoftware.com', imageUrl: 'https://picsum.photos/seed/ginger/400/250', rating: 4.6, reviewCount: 3100, clickCount: 52000, favoritesCount: 18000, isVipEnabled: false, pricing: 'Freemium', reviews: [], status: 'approved', origin: 'Global' },
  { id: 'prowritingaid', name: 'ProWritingAid', description: '专业作家首选的长文修改专家。', category: 'Writing', tags: ['Pro'], url: 'https://prowritingaid.com', imageUrl: 'https://picsum.photos/seed/pwa/400/250', rating: 4.85, reviewCount: 1200, clickCount: 38000, favoritesCount: 12000, isVipEnabled: false, pricing: 'Paid', reviews: [], status: 'approved', origin: 'Global' },
  { id: 'copysmith', name: 'CopySmith', description: '为电商团队定制的批量描述生成。', category: 'Writing', tags: ['Ecom'], url: 'https://copysmith.ai', imageUrl: 'https://picsum.photos/seed/csmith/400/250', rating: 4.5, reviewCount: 850, clickCount: 18000, favoritesCount: 7200, isVipEnabled: false, pricing: 'Paid', reviews: [], status: 'approved', origin: 'Global' },
  { id: 'peppertype', name: 'Peppertype', description: '极速生成各类短文案与社交内容。', category: 'Writing', tags: ['Social'], url: 'https://peppertype.ai', imageUrl: 'https://picsum.photos/seed/pepper/400/250', rating: 4.6, reviewCount: 420, clickCount: 12000, favoritesCount: 5200, isVipEnabled: false, pricing: 'Paid', reviews: [], status: 'approved', origin: 'Global' },
  { id: 'contentbot', name: 'ContentBot', description: '全流程内容创作流自动化。', category: 'Writing', tags: ['Workflow'], url: 'https://contentbot.ai', imageUrl: 'https://picsum.photos/seed/cbot/400/250', rating: 4.55, reviewCount: 310, clickCount: 9200, favoritesCount: 3100, isVipEnabled: false, pricing: 'Paid', reviews: [], status: 'approved', origin: 'Global' },
  { id: 'hypotenuse', name: 'Hypotenuse AI', description: '自动根据标题生成结构化博文。', category: 'Writing', tags: ['Blog'], url: 'https://hypotenuse.ai', imageUrl: 'https://picsum.photos/seed/hyp/400/250', rating: 4.7, reviewCount: 520, clickCount: 15000, favoritesCount: 6500, isVipEnabled: false, pricing: 'Paid', reviews: [], status: 'approved', origin: 'Global' },
  { id: 'jasper-write', name: 'Jasper (Writing Hub)', description: '行业公认的企业级写作金标准。', category: 'Writing', tags: ['Standard'], url: 'https://jasper.ai', imageUrl: 'https://picsum.photos/seed/jasper/400/250', rating: 4.9, reviewCount: 22000, clickCount: 450000, favoritesCount: 180000, isVipEnabled: false, pricing: 'Paid', reviews: [], status: 'approved', origin: 'Global' },

  // --- DESIGN & UI (9 tools) ---
  { id: 'adobe-express', name: 'Adobe Express', description: '零门槛 AI 平面设计专家。', category: 'Design & UI', tags: ['Adobe'], url: 'https://adobe.com/express', imageUrl: 'https://picsum.photos/seed/adxp/400/250', rating: 4.85, reviewCount: 15000, clickCount: 350000, favoritesCount: 120000, isVipEnabled: false, pricing: 'Freemium', reviews: [], status: 'approved', origin: 'Global' },
  { id: 'ms-designer', name: 'Microsoft Designer', description: '微软出品，一键生成精美社媒图。', category: 'Design & UI', tags: ['MS'], url: 'https://designer.microsoft.com', imageUrl: 'https://picsum.photos/seed/msd/400/250', rating: 4.7, reviewCount: 8200, clickCount: 210000, favoritesCount: 85000, isVipEnabled: false, pricing: 'Free', reviews: [], status: 'approved', origin: 'Global' },
  { id: 'khroma', name: 'Khroma', description: '学习你的品味，生成专属配色方案。', category: 'Design & UI', tags: ['Color'], url: 'https://khroma.co', imageUrl: 'https://picsum.photos/seed/khr/400/250', rating: 4.75, reviewCount: 520, clickCount: 12000, favoritesCount: 4200, isVipEnabled: false, pricing: 'Free', reviews: [], status: 'approved', origin: 'Global' },
  { id: 'hb-meisi', name: '花瓣美思灵感', description: '国内最大的素材站推出的 AI 版。', category: 'Design & UI', tags: ['China'], url: 'https://huaban.com', imageUrl: 'https://picsum.photos/seed/hbm/400/250', rating: 4.82, reviewCount: 3100, clickCount: 85000, favoritesCount: 32000, isVipEnabled: false, pricing: 'Freemium', reviews: [], status: 'approved', origin: 'China' },
  { id: 'mastergo', name: 'MasterGo AI', description: '国产专业 UI 协作，集成智能排版。', category: 'Design & UI', tags: ['China'], url: 'https://mastergo.com', imageUrl: 'https://picsum.photos/seed/mgo/400/250', rating: 4.8, reviewCount: 5400, clickCount: 120000, favoritesCount: 45000, isVipEnabled: false, pricing: 'Freemium', reviews: [], status: 'approved', origin: 'China' },
  { id: 'jishi', name: '即时设计 AI', description: '手绘草图秒变可交互原型。', category: 'Design & UI', tags: ['China'], url: 'https://js.design', imageUrl: 'https://picsum.photos/seed/jsd/400/250', rating: 4.88, reviewCount: 4200, clickCount: 95000, favoritesCount: 38000, isVipEnabled: false, pricing: 'Freemium', reviews: [], status: 'approved', origin: 'China' },
  { id: 'looka', name: 'Looka Logo Maker', description: '全自动、智能化的品牌 Logo 生成。', category: 'Design & UI', tags: ['Logo'], url: 'https://looka.com', imageUrl: 'https://picsum.photos/seed/looka/400/250', rating: 4.6, reviewCount: 2100, clickCount: 38000, favoritesCount: 12000, isVipEnabled: false, pricing: 'Paid', reviews: [], status: 'approved', origin: 'Global' },
  { id: 'brandmark', name: 'Brandmark', description: '极简风格的企业视觉识别系统生成。', category: 'Design & UI', tags: ['Brand'], url: 'https://brandmark.io', imageUrl: 'https://picsum.photos/seed/bm/400/250', rating: 4.5, reviewCount: 850, clickCount: 15000, favoritesCount: 5200, isVipEnabled: false, pricing: 'Paid', reviews: [], status: 'approved', origin: 'Global' },
  { id: 'tailorbrands', name: 'Tailor Brands', description: '为中小企业打造的 AI 设计全家桶。', category: 'Design & UI', tags: ['AllInOne'], url: 'https://tailorbrands.com', imageUrl: 'https://picsum.photos/seed/tb/400/250', rating: 4.4, reviewCount: 12000, clickCount: 180000, favoritesCount: 65000, isVipEnabled: false, pricing: 'Paid', reviews: [], status: 'approved', origin: 'Global' },

  // --- EDUCATION (9 tools) ---
  { id: 'photomath', name: 'Photomath', description: '拍照秒解数学题并提供解析。', category: 'Education', tags: ['Math'], url: 'https://photomath.com', imageUrl: 'https://picsum.photos/seed/pmath/400/250', rating: 4.95, reviewCount: 250000, clickCount: 5000000, favoritesCount: 1500000, isVipEnabled: false, pricing: 'Freemium', reviews: [], status: 'approved', origin: 'Global' },
  { id: 'elsa', name: 'ELSA Speak', description: '最精准的 AI 英语口语纠音助理。', category: 'Education', tags: ['English'], url: 'https://elsaspeak.com', imageUrl: 'https://picsum.photos/seed/elsa/400/250', rating: 4.9, reviewCount: 15000, clickCount: 850000, favoritesCount: 320000, isVipEnabled: false, pricing: 'Freemium', reviews: [], status: 'approved', origin: 'Global' },
  { id: 'speakai', name: 'Speak AI', description: '沉浸式 AI 角色扮演外教对话。', category: 'Education', tags: ['Language'], url: 'https://speak.com', imageUrl: 'https://picsum.photos/seed/speak/400/250', rating: 4.88, reviewCount: 8200, clickCount: 420000, favoritesCount: 150000, isVipEnabled: false, pricing: 'Paid', reviews: [], status: 'approved', origin: 'Global' },
  { id: 'questionwell', name: 'QuestionWell', description: '自动根据课文生成多类型测试题。', category: 'Education', tags: ['Teacher'], url: 'https://questionwell.org', imageUrl: 'https://picsum.photos/seed/qw/400/250', rating: 4.7, reviewCount: 520, clickCount: 12000, favoritesCount: 4200, isVipEnabled: false, pricing: 'Freemium', reviews: [], status: 'approved', origin: 'Global' },
  { id: 'curipod', name: 'Curipod', description: 'AI 生成互动课堂幻灯片与活动。', category: 'Education', tags: ['ActiveLearning'], url: 'https://curipod.com', imageUrl: 'https://picsum.photos/seed/curi/400/250', rating: 4.8, reviewCount: 310, clickCount: 8200, favoritesCount: 2800, isVipEnabled: false, pricing: 'Freemium', reviews: [], status: 'approved', origin: 'Global' },
  { id: 'formative', name: 'Formative AI', description: '实时跟进并分析学生的学习进展。', category: 'Education', tags: ['Data'], url: 'https://formative.com', imageUrl: 'https://picsum.photos/seed/form/400/250', rating: 4.65, reviewCount: 120, clickCount: 3500, favoritesCount: 1100, isVipEnabled: false, pricing: 'Freemium', reviews: [], status: 'approved', origin: 'Global' },
  { id: 'quizlet', name: 'Quizlet Magic Notes', description: '笔记秒变记忆卡片与练习。', category: 'Education', tags: ['Study'], url: 'https://quizlet.com', imageUrl: 'https://picsum.photos/seed/quiz/400/250', rating: 4.9, reviewCount: 120000, clickCount: 3500000, favoritesCount: 1200000, isVipEnabled: false, pricing: 'Freemium', reviews: [], status: 'approved', origin: 'Global' },
  { id: 'socratic', name: 'Socratic (Google)', description: '基于 AI 的全学科作业解答助手。', category: 'Education', tags: ['Homework'], url: 'https://socratic.org', imageUrl: 'https://picsum.photos/seed/soc/400/250', rating: 4.85, reviewCount: 85000, clickCount: 2100000, favoritesCount: 850000, isVipEnabled: false, pricing: 'Free', reviews: [], status: 'approved', origin: 'Global' },
  { id: 'chegg', name: 'Chegg AI', description: '老牌教辅平台的智能化全面升级。', category: 'Education', tags: ['Classic'], url: 'https://chegg.com', imageUrl: 'https://picsum.photos/seed/chegg/400/250', rating: 4.4, reviewCount: 52000, clickCount: 1500000, favoritesCount: 420000, isVipEnabled: false, pricing: 'Paid', reviews: [], status: 'approved', origin: 'Global' },

  // --- TRANSLATION (9 tools) ---
  { id: 'deepl', name: 'DeepL', description: '公认的全球翻译精准度第一。', category: 'Translation', tags: ['Leader'], url: 'https://deepl.com', imageUrl: 'https://picsum.photos/seed/deepl/400/250', rating: 4.98, reviewCount: 150000, clickCount: 8500000, favoritesCount: 4200000, isVipEnabled: false, pricing: 'Freemium', reviews: [], status: 'approved', origin: 'Global' },
  { id: 'immersive', name: '沉浸式翻译', description: '国产翻译插件之光，改变阅读体验。', category: 'Translation', tags: ['China'], url: 'https://immersivetranslate.com', imageUrl: 'https://picsum.photos/seed/immersive/400/250', rating: 4.99, reviewCount: 52000, clickCount: 2500000, favoritesCount: 1200000, isVipEnabled: false, pricing: 'Freemium', reviews: [], status: 'approved', origin: 'China' },
  { id: 'rask', name: 'Rask.ai', description: '视频翻译、配音、口型同步一站式。', category: 'Translation', tags: ['Video'], url: 'https://rask.ai', imageUrl: 'https://picsum.photos/seed/rask/400/250', rating: 4.9, reviewCount: 1500, clickCount: 85000, favoritesCount: 32000, isVipEnabled: false, pricing: 'Paid', reviews: [], status: 'approved', origin: 'Global' },
  { id: 'tx-fanyi', name: '腾讯翻译君', description: '国产专业口译与实时同传专家。', category: 'Translation', tags: ['China'], url: 'https://fanyi.qq.com', imageUrl: 'https://picsum.photos/seed/txf/400/250', rating: 4.75, reviewCount: 32000, clickCount: 1500000, favoritesCount: 420000, isVipEnabled: false, pricing: 'Free', reviews: [], status: 'approved', origin: 'China' },
  { id: 'bd-fanyi', name: '百度翻译 AI', description: '深度集成文心一言，语境理解更强。', category: 'Translation', tags: ['China'], url: 'https://fanyi.baidu.com', imageUrl: 'https://picsum.photos/seed/bdf/400/250', rating: 4.65, reviewCount: 120000, clickCount: 5000000, favoritesCount: 1500000, isVipEnabled: false, pricing: 'Freemium', reviews: [], status: 'approved', origin: 'China' },
  { id: 'g-translate', name: 'Google Translate', description: '覆盖语言最全，基础翻译稳固。', category: 'Translation', tags: ['AllLang'], url: 'https://translate.google.com', imageUrl: 'https://picsum.photos/seed/gt/400/250', rating: 4.6, reviewCount: 500000, clickCount: 15000000, favoritesCount: 3500000, isVipEnabled: false, pricing: 'Free', reviews: [], status: 'approved', origin: 'Global' },
  { id: 'lingvanex', name: 'Lingvanex', description: '多端同步，离线翻译能力突出。', category: 'Translation', tags: ['Offline'], url: 'https://lingvanex.com', imageUrl: 'https://picsum.photos/seed/ling/400/250', rating: 4.55, reviewCount: 520, clickCount: 15000, favoritesCount: 5200, isVipEnabled: false, pricing: 'Paid', reviews: [], status: 'approved', origin: 'Global' },
  { id: 'cy-fanyi', name: '彩云小译', description: '极具口碑的国产沉浸式双语同传。', category: 'Translation', tags: ['China'], url: 'https://caiyunapp.com', imageUrl: 'https://picsum.photos/seed/cy/400/250', rating: 4.88, reviewCount: 8500, clickCount: 450000, favoritesCount: 120000, isVipEnabled: false, pricing: 'Freemium', reviews: [], status: 'approved', origin: 'China' },
  { id: 'unbabel', name: 'Unbabel', description: 'AI + 人工审核，企业级精准翻译。', category: 'Translation', tags: ['Enterprise'], url: 'https://unbabel.com', imageUrl: 'https://picsum.photos/seed/unb/400/250', rating: 4.7, reviewCount: 210, clickCount: 5200, favoritesCount: 1800, isVipEnabled: false, pricing: 'Paid', reviews: [], status: 'approved', origin: 'Global' },

  // --- FINANCE (9 tools) ---
  { id: 'alphasense', name: 'AlphaSense', description: '华尔街投行必备的市场智能搜索引擎。', category: 'Finance', tags: ['Insight'], url: 'https://alpha-sense.com', imageUrl: 'https://picsum.photos/seed/alpha/400/250', rating: 4.95, reviewCount: 310, clickCount: 15000, favoritesCount: 6500, isVipEnabled: false, pricing: 'Paid', reviews: [], status: 'approved', origin: 'Global' },
  { id: 'kavout', name: 'Kavout', description: 'AI 驱动的量化评分与股票信号。', category: 'Finance', tags: ['Quant'], url: 'https://kavout.com', imageUrl: 'https://picsum.photos/seed/kav/400/250', rating: 4.7, reviewCount: 120, clickCount: 4200, favoritesCount: 1500, isVipEnabled: false, pricing: 'Paid', reviews: [], status: 'approved', origin: 'Global' },
  { id: 'finchat', name: 'FinChat.io', description: '上市公司财务报告的对话式百科全书。', category: 'Finance', tags: ['Data'], url: 'https://finchat.io', imageUrl: 'https://picsum.photos/seed/fin/400/250', rating: 4.88, reviewCount: 420, clickCount: 12000, favoritesCount: 5200, isVipEnabled: false, pricing: 'Freemium', reviews: [], status: 'approved', origin: 'Global' },
  { id: 'tickeron', name: 'Tickeron', description: '通过 AI 模式识别预测股市趋势。', category: 'Finance', tags: ['Algorithm'], url: 'https://tickeron.com', imageUrl: 'https://picsum.photos/seed/tick/400/250', rating: 4.6, reviewCount: 85, clickCount: 5200, favoritesCount: 1800, isVipEnabled: false, pricing: 'Paid', reviews: [], status: 'approved', origin: 'Global' },
  { id: 'bloomberg', name: 'BloombergGPT', description: '彭博终端内置的顶级金融垂直大模型。', category: 'Finance', tags: ['Leader'], url: 'https://bloomberg.com', imageUrl: 'https://picsum.photos/seed/bbg/400/250', rating: 4.98, reviewCount: 50, clickCount: 1200, favoritesCount: 850, isVipEnabled: false, pricing: 'Paid', reviews: [], status: 'approved', origin: 'Global' },
  { id: 'sentieo', name: 'Sentieo', description: '金融分析师的高级研究工作台。', category: 'Finance', tags: ['Workstation'], url: 'https://sentieo.com', imageUrl: 'https://picsum.photos/seed/sen/400/250', rating: 4.82, reviewCount: 150, clickCount: 3500, favoritesCount: 1200, isVipEnabled: false, pricing: 'Paid', reviews: [], status: 'approved', origin: 'Global' },
  { id: 'wealthfront', name: 'Wealthfront AI', description: '全自动、智能化的资产配置专家。', category: 'Finance', tags: ['RoboAdvisor'], url: 'https://wealthfront.com', imageUrl: 'https://picsum.photos/seed/wf/400/250', rating: 4.75, reviewCount: 85000, clickCount: 1500000, favoritesCount: 420000, isVipEnabled: false, pricing: 'Paid', reviews: [], status: 'approved', origin: 'Global' },
  { id: 'betterment', name: 'Betterment AI', description: '智能投资组合管理与税务优化。', category: 'Finance', tags: ['TaxLoss'], url: 'https://betterment.com', imageUrl: 'https://picsum.photos/seed/bet/400/250', rating: 4.7, reviewCount: 65000, clickCount: 1200000, favoritesCount: 350000, isVipEnabled: false, pricing: 'Paid', reviews: [], status: 'approved', origin: 'Global' },
  { id: 'tradeideas', name: 'Trade Ideas', description: 'AI 驱动的实时股票交易扫描仪。', category: 'Finance', tags: ['Live'], url: 'https://trade-ideas.com', imageUrl: 'https://picsum.photos/seed/trade/400/250', rating: 4.85, reviewCount: 2100, clickCount: 45000, favoritesCount: 18000, isVipEnabled: false, pricing: 'Paid', reviews: [], status: 'approved', origin: 'Global' },

  // --- LEGAL (9 tools) ---
  { id: 'lexis-ai', name: 'Lexis+ AI', description: '老牌法律数据库的生成式 AI 终极版。', category: 'Legal', tags: ['Database'], url: 'https://lexisnexis.com', imageUrl: 'https://picsum.photos/seed/lex/400/250', rating: 4.9, reviewCount: 850, clickCount: 12000, favoritesCount: 5200, isVipEnabled: false, pricing: 'Paid', reviews: [], status: 'approved', origin: 'Global' },
  { id: 'spellbook', name: 'Spellbook', description: '深度集成于 Word 的合同起草 AI。', category: 'Legal', tags: ['Contract'], url: 'https://spellbook.legal', imageUrl: 'https://picsum.photos/seed/spell/400/250', rating: 4.88, reviewCount: 310, clickCount: 15000, favoritesCount: 6200, isVipEnabled: false, pricing: 'Paid', reviews: [], status: 'approved', origin: 'Global' },
  { id: 'harvey', name: 'Harvey AI', description: '全球顶级律所（如普华永道）钦定的 AI。', category: 'Legal', tags: ['Exclusive'], url: 'https://harvey.ai', imageUrl: 'https://picsum.photos/seed/harvey/400/250', rating: 4.96, reviewCount: 120, clickCount: 5200, favoritesCount: 2100, isVipEnabled: false, pricing: 'Paid', reviews: [], status: 'approved', origin: 'Global' },
  { id: 'casetext', name: 'Casetext CoCounsel', description: '首个法律 AI 助手，处理复杂证据分析。', category: 'Legal', tags: ['Analysis'], url: 'https://casetext.com', imageUrl: 'https://picsum.photos/seed/case/400/250', rating: 4.92, reviewCount: 520, clickCount: 18000, favoritesCount: 8200, isVipEnabled: false, pricing: 'Paid', reviews: [], status: 'approved', origin: 'Global' },
  { id: 'ironclad', name: 'Ironclad AI', description: '企业级合同全生命周期智能管理。', category: 'Legal', tags: ['Lifecycle'], url: 'https://ironcladapp.com', imageUrl: 'https://picsum.photos/seed/iron/400/250', rating: 4.75, reviewCount: 1500, clickCount: 32000, favoritesCount: 11000, isVipEnabled: false, pricing: 'Paid', reviews: [], status: 'approved', origin: 'Global' },
  { id: 'luminance', name: 'Luminance', description: 'AI 驱动的尽职调查与合规检查。', category: 'Legal', tags: ['Audit'], url: 'https://luminance.com', imageUrl: 'https://picsum.photos/seed/lum/400/250', rating: 4.7, reviewCount: 420, clickCount: 12000, favoritesCount: 4500, isVipEnabled: false, pricing: 'Paid', reviews: [], status: 'approved', origin: 'Global' },
  { id: 'lawgeex', name: 'LawGeex', description: '自动审查并标记合同中的风险点。', category: 'Legal', tags: ['Risk'], url: 'https://lawgeex.com', imageUrl: 'https://picsum.photos/seed/lawg/400/250', rating: 4.6, reviewCount: 280, clickCount: 9200, favoritesCount: 3100, isVipEnabled: false, pricing: 'Paid', reviews: [], status: 'approved', origin: 'Global' },
  { id: 'evenup', name: 'EvenUp', description: '专注个人伤害理赔的法律文书 AI。', category: 'Legal', tags: ['Specialized'], url: 'https://evenupestates.com', imageUrl: 'https://picsum.photos/seed/even/400/250', rating: 4.85, reviewCount: 120, clickCount: 4500, favoritesCount: 1900, isVipEnabled: false, pricing: 'Paid', reviews: [], status: 'approved', origin: 'Global' },
  { id: 'fali', name: '法里 AI', description: '国产法律知识百科与智能咨询。', category: 'Legal', tags: ['China'], url: 'https://fali.ai', imageUrl: 'https://picsum.photos/seed/fali/400/250', rating: 4.72, reviewCount: 8500, clickCount: 120000, favoritesCount: 35000, isVipEnabled: false, pricing: 'Freemium', reviews: [], status: 'approved', origin: 'China' },

  // --- MEDICAL (9 tools) ---
  { id: 'glass-health', name: 'Glass Health', description: 'AI 辅助医生进行临床诊断规划。', category: 'Medical', tags: ['Clinical'], url: 'https://glass.health', imageUrl: 'https://picsum.photos/seed/glass/400/250', rating: 4.9, reviewCount: 310, clickCount: 12000, favoritesCount: 5200, isVipEnabled: false, pricing: 'Paid', reviews: [], status: 'approved', origin: 'Global' },
  { id: 'ada', name: 'Ada', description: '全球最顶尖的自诊 AI 助手。', category: 'Medical', tags: ['Checkup'], url: 'https://ada.com', imageUrl: 'https://picsum.photos/seed/ada/400/250', rating: 4.85, reviewCount: 25000, clickCount: 850000, favoritesCount: 410000, isVipEnabled: false, pricing: 'Free', reviews: [], status: 'approved', origin: 'Global' },
  { id: 'forward', name: 'Forward CarePod', description: 'AI 驱动的无人自动化诊室。', category: 'Medical', tags: ['Hardware'], url: 'https://goforward.com', imageUrl: 'https://picsum.photos/seed/fwd/400/250', rating: 4.95, reviewCount: 150, clickCount: 45000, favoritesCount: 18000, isVipEnabled: false, pricing: 'Paid', reviews: [], status: 'approved', origin: 'Global' },
  { id: 'tencent-miying', name: '腾讯觅影', description: '国产 AI 影像辅助诊断的标杆。', category: 'Medical', tags: ['China'], url: 'https://miying.qq.com', imageUrl: 'https://picsum.photos/seed/tmy/400/250', rating: 4.92, reviewCount: 1200, clickCount: 150000, favoritesCount: 52000, isVipEnabled: false, pricing: 'Paid', reviews: [], status: 'approved', origin: 'China' },
  { id: 'jd-health', name: '京东健康京医千询', description: '京东医疗大模型服务体系。', category: 'Medical', tags: ['China'], url: 'https://health.jd.com', imageUrl: 'https://picsum.photos/seed/jdh/400/250', rating: 4.75, reviewCount: 35000, clickCount: 1200000, favoritesCount: 450000, isVipEnabled: false, pricing: 'Free', reviews: [], status: 'approved', origin: 'China' },
  { id: 'bd-lingyi', name: '百度灵医', description: '百度垂直医疗大模型应用。', category: 'Medical', tags: ['China'], url: 'https://lingyi.baidu.com', imageUrl: 'https://picsum.photos/seed/bdl/400/250', rating: 4.8, reviewCount: 18000, clickCount: 650000, favoritesCount: 210000, isVipEnabled: false, pricing: 'Free', reviews: [], status: 'approved', origin: 'China' },
  { id: 'vizai', name: 'Viz.ai', description: '中风等紧急医疗状况的 AI 预警系统。', category: 'Medical', tags: ['Emergency'], url: 'https://viz.ai', imageUrl: 'https://picsum.photos/seed/viz/400/250', rating: 4.88, reviewCount: 850, clickCount: 12000, favoritesCount: 4500, isVipEnabled: false, pricing: 'Paid', reviews: [], status: 'approved', origin: 'Global' },
  { id: 'regard', name: 'Regard AI', description: '自动诊断与临床文档生成的专家。', category: 'Medical', tags: ['Diagnostics'], url: 'https://withregard.com', imageUrl: 'https://picsum.photos/seed/reg/400/250', rating: 4.8, reviewCount: 210, clickCount: 5200, favoritesCount: 1800, isVipEnabled: false, pricing: 'Paid', reviews: [], status: 'approved', origin: 'Global' },
  { id: 'babylon', name: 'Babylon Health', description: '全方位的数字健康管理平台。', category: 'Medical', tags: ['HealthHub'], url: 'https://babylonhealth.com', imageUrl: 'https://picsum.photos/seed/bab/400/250', rating: 4.5, reviewCount: 52000, clickCount: 880000, favoritesCount: 220000, isVipEnabled: false, pricing: 'Freemium', reviews: [], status: 'approved', origin: 'Global' },

  // --- AGENT FRAMEWORKS (9 tools) ---
  { id: 'langchain', name: 'LangChain', description: 'LLM 应用开发的全球通用标准框架。', category: 'Agent Frameworks', tags: ['Dev'], url: 'https://langchain.com', imageUrl: 'https://picsum.photos/seed/lc/400/250', rating: 4.95, reviewCount: 25000, clickCount: 150000, favoritesCount: 72000, isVipEnabled: false, pricing: 'Free', reviews: [], status: 'approved', origin: 'Global' },
  { id: 'dify', name: 'Dify.ai', description: '国产最火开源 Agent 开发平台。', category: 'Agent Frameworks', tags: ['China'], url: 'https://dify.ai', imageUrl: 'https://picsum.photos/seed/dify/400/250', rating: 4.98, reviewCount: 18000, clickCount: 95000, favoritesCount: 45000, isVipEnabled: false, pricing: 'Freemium', reviews: [], status: 'approved', origin: 'China' },
  { id: 'autogen', name: 'AutoGen (Microsoft)', description: '微软出品，多智能体协作框架。', category: 'Agent Frameworks', tags: ['MultiAgent'], url: 'https://microsoft.github.io/autogen/', imageUrl: 'https://picsum.photos/seed/autogen/400/250', rating: 4.92, reviewCount: 5400, clickCount: 42000, favoritesCount: 21000, isVipEnabled: false, pricing: 'Free', reviews: [], status: 'approved', origin: 'Global' },
  { id: 'coze-dev', name: '扣子 (Coze)', description: '字节跳动推出的零代码 Agent 平台。', category: 'Agent Frameworks', tags: ['China'], url: 'https://www.coze.cn', imageUrl: 'https://picsum.photos/seed/cozed/400/250', rating: 4.96, reviewCount: 35000, clickCount: 280000, favoritesCount: 120000, isVipEnabled: false, pricing: 'Free', reviews: [], status: 'approved', origin: 'China' },
  { id: 'crewai', name: 'CrewAI', description: '基于角色的多智能体管弦乐编排。', category: 'Agent Frameworks', tags: ['Orchestration'], url: 'https://crewai.com', imageUrl: 'https://picsum.photos/seed/crew/400/250', rating: 4.85, reviewCount: 4200, clickCount: 35000, favoritesCount: 15000, isVipEnabled: false, pricing: 'Free', reviews: [], status: 'approved', origin: 'Global' },
  { id: 'babyagi', name: 'BabyAGI', description: '简洁、经典的自主智能体原型。', category: 'Agent Frameworks', tags: ['Classic'], url: 'https://github.com/yoheinakajima/babyagi', imageUrl: 'https://picsum.photos/seed/baby/400/250', rating: 4.7, reviewCount: 1500, clickCount: 52000, favoritesCount: 18000, isVipEnabled: false, pricing: 'Free', reviews: [], status: 'approved', origin: 'Global' },
  { id: 'linkai', name: 'LinkAI', description: '国产企业级 Agent 快速集成平台。', category: 'Agent Frameworks', tags: ['China'], url: 'https://link-ai.tech', imageUrl: 'https://picsum.photos/seed/link/400/250', rating: 4.82, reviewCount: 1200, clickCount: 18000, favoritesCount: 6500, isVipEnabled: false, pricing: 'Freemium', reviews: [], status: 'approved', origin: 'China' },
  { id: 'superagi', name: 'SuperAGI', description: '开发者优先的自主 Agent 基础设施。', category: 'Agent Frameworks', tags: ['Infra'], url: 'https://superagi.com', imageUrl: 'https://picsum.photos/seed/super/400/250', rating: 4.75, reviewCount: 850, clickCount: 12000, favoritesCount: 4200, isVipEnabled: false, pricing: 'Free', reviews: [], status: 'approved', origin: 'Global' },
  { id: 'kernel', name: 'Semantic Kernel', description: '微软官方 LLM 与代码集成 SDK。', category: 'Agent Frameworks', tags: ['MSFT'], url: 'https://github.com/microsoft/semantic-kernel', imageUrl: 'https://picsum.photos/seed/kernel/400/250', rating: 4.8, reviewCount: 3100, clickCount: 25000, favoritesCount: 11000, isVipEnabled: false, pricing: 'Free', reviews: [], status: 'approved', origin: 'Global' },

  // --- CHARACTER & SOCIAL (9 tools) ---
  { id: 'character', name: 'Character.ai', description: '全球最火的角色社交与扮演平台。', category: 'Character & Social', tags: ['Social'], url: 'https://character.ai', imageUrl: 'https://picsum.photos/seed/cai/400/250', rating: 4.95, reviewCount: 150000, clickCount: 8500000, favoritesCount: 3500000, isVipEnabled: false, pricing: 'Freemium', reviews: [], status: 'approved', origin: 'Global' },
  { id: 'replika', name: 'Replika', description: '你的 AI 虚拟灵魂伴侣。', category: 'Character & Social', tags: ['Companion'], url: 'https://replika.com', imageUrl: 'https://picsum.photos/seed/repl/400/250', rating: 4.8, reviewCount: 85000, clickCount: 2500000, favoritesCount: 850000, isVipEnabled: false, pricing: 'Freemium', reviews: [], status: 'approved', origin: 'Global' },
  { id: 'xingye', name: '星野 (Glow)', description: '国产沉浸式 AI 社交之王。', category: 'Character & Social', tags: ['China'], url: 'https://xingye.ai', imageUrl: 'https://picsum.photos/seed/xy/400/250', rating: 4.98, reviewCount: 120000, clickCount: 5000000, favoritesCount: 2100000, isVipEnabled: false, pricing: 'Free', reviews: [], status: 'approved', origin: 'China' },
  { id: 'hualu', name: '话炉', description: '字节跳动推出的情感社交 AI。', category: 'Character & Social', tags: ['China'], url: 'https://hualu.com', imageUrl: 'https://picsum.photos/seed/hl/400/250', rating: 4.92, reviewCount: 52000, clickCount: 1500000, favoritesCount: 680000, isVipEnabled: false, pricing: 'Free', reviews: [], status: 'approved', origin: 'China' },
  { id: 'wanhua', name: '百度万话', description: '百度出品的虚拟角色对话。', category: 'Character & Social', tags: ['China'], url: 'https://wanhua.baidu.com', imageUrl: 'https://picsum.photos/seed/wh/400/250', rating: 4.85, reviewCount: 32000, clickCount: 950000, favoritesCount: 420000, isVipEnabled: false, pricing: 'Free', reviews: [], status: 'approved', origin: 'China' },
  { id: 'chai', name: 'Chai', description: '无限制、高自由度的角色对话。', category: 'Character & Social', tags: ['Open'], url: 'https://chai.ml', imageUrl: 'https://picsum.photos/seed/chai/400/250', rating: 4.7, reviewCount: 45000, clickCount: 1200000, favoritesCount: 520000, isVipEnabled: false, pricing: 'Freemium', reviews: [], status: 'approved', origin: 'Global' },
  { id: 'poly', name: 'Poly.ai', description: '智能、动人的 AI 角色交互。', category: 'Character & Social', tags: ['Creative'], url: 'https://poly.ai', imageUrl: 'https://picsum.photos/seed/poly/400/250', rating: 4.65, reviewCount: 12000, clickCount: 350000, favoritesCount: 150000, isVipEnabled: false, pricing: 'Freemium', reviews: [], status: 'approved', origin: 'Global' },
  { id: 'inworld', name: 'Inworld', description: '为元宇宙打造的深度 AI NPC。', category: 'Character & Social', tags: ['Metaverse'], url: 'https://inworld.ai', imageUrl: 'https://picsum.photos/seed/inw/400/250', rating: 4.88, reviewCount: 520, clickCount: 12000, favoritesCount: 4500, isVipEnabled: false, pricing: 'Paid', reviews: [], status: 'approved', origin: 'Global' },
  { id: 'zmd', name: '阅文筑梦岛', description: '国产正版小说角色交互圣地。', category: 'Character & Social', tags: ['China'], url: 'https://zhumengdao.com', imageUrl: 'https://picsum.photos/seed/zmd/400/250', rating: 4.82, reviewCount: 15000, clickCount: 450000, favoritesCount: 180000, isVipEnabled: false, pricing: 'Free', reviews: [], status: 'approved', origin: 'China' },

  // --- DEVELOPER TOOLS (9 tools) ---
  { id: 'pinecone', name: 'Pinecone', description: '最受欢迎的向量数据库，RAG 必备。', category: 'Developer Tools', tags: ['Vector'], url: 'https://pinecone.io', imageUrl: 'https://picsum.photos/seed/pine/400/250', rating: 4.92, reviewCount: 1200, clickCount: 50000, favoritesCount: 22000, isVipEnabled: false, pricing: 'Freemium', reviews: [], status: 'approved', origin: 'Global' },
  { id: 'wandb', name: 'Weights & Biases', description: '机器学习实验跟踪与可视化的黄金标准。', category: 'Developer Tools', tags: ['MLOps'], url: 'https://wandb.ai', imageUrl: 'https://picsum.photos/seed/wb/400/250', rating: 4.94, reviewCount: 3100, clickCount: 85000, favoritesCount: 38000, isVipEnabled: false, pricing: 'Freemium', reviews: [], status: 'approved', origin: 'Global' },
  { id: 'langsmith', name: 'LangSmith', description: 'LLM 应用调试、测试与监控。', category: 'Developer Tools', tags: ['Testing'], url: 'https://smith.langchain.com', imageUrl: 'https://picsum.photos/seed/ls/400/250', rating: 4.9, reviewCount: 850, clickCount: 12000, favoritesCount: 4500, isVipEnabled: false, pricing: 'Freemium', reviews: [], status: 'approved', origin: 'Global' },
  { id: 'zilliz', name: 'Zilliz (Milvus)', description: '国产顶级开源向量数据库。', category: 'Developer Tools', tags: ['China'], url: 'https://zilliz.com', imageUrl: 'https://picsum.photos/seed/zil/400/250', rating: 4.88, reviewCount: 1500, clickCount: 25000, favoritesCount: 11000, isVipEnabled: false, pricing: 'Freemium', reviews: [], status: 'approved', origin: 'China' },
  { id: 'baichuan-dev', name: '百川开发者平台', description: '王小川出品，国产 API 服务标杆。', category: 'Developer Tools', tags: ['China'], url: 'https://baichuan-ai.com', imageUrl: 'https://picsum.photos/seed/bc/400/250', rating: 4.85, reviewCount: 5200, clickCount: 85000, favoritesCount: 32000, isVipEnabled: false, pricing: 'Paid', reviews: [], status: 'approved', origin: 'China' },
  { id: 'helicone', name: 'Helicone', description: '可观测性极佳的开源 LLM 监控。', category: 'Developer Tools', tags: ['Analytics'], url: 'https://helicone.ai', imageUrl: 'https://picsum.photos/seed/heli/400/250', rating: 4.8, reviewCount: 310, clickCount: 5200, favoritesCount: 1800, isVipEnabled: false, pricing: 'Freemium', reviews: [], status: 'approved', origin: 'Global' },
  { id: 'weaviate', name: 'Weaviate', description: '模块化、可扩展的向量搜索引擎。', category: 'Developer Tools', tags: ['Search'], url: 'https://weaviate.io', imageUrl: 'https://picsum.photos/seed/weav/400/250', rating: 4.75, reviewCount: 2100, clickCount: 35000, favoritesCount: 15000, isVipEnabled: false, pricing: 'Free', reviews: [], status: 'approved', origin: 'Global' },
  { id: 'together', name: 'Together AI', description: '最高性价比的开源模型托管云。', category: 'Developer Tools', tags: ['Inference'], url: 'https://together.ai', imageUrl: 'https://picsum.photos/seed/together/400/250', rating: 4.82, reviewCount: 520, clickCount: 15000, favoritesCount: 7200, isVipEnabled: false, pricing: 'Paid', reviews: [], status: 'approved', origin: 'Global' },
  { id: 'mindspore', name: '昇思 MindSpore', description: '华为自研国产全场景 AI 计算框架。', category: 'Developer Tools', tags: ['China'], url: 'https://mindspore.cn', imageUrl: 'https://picsum.photos/seed/ms/400/250', rating: 4.6, reviewCount: 85000, clickCount: 1500000, favoritesCount: 520000, isVipEnabled: false, pricing: 'Free', reviews: [], status: 'approved', origin: 'China' },

  // --- GAMING AI (9 tools) ---
  { id: 'ludo', name: 'Ludo.ai', description: 'AI 驱动的游戏策划与市场情报。', category: 'Gaming AI', tags: ['Idea'], url: 'https://ludo.ai', imageUrl: 'https://picsum.photos/seed/ludo/400/250', rating: 4.8, reviewCount: 310, clickCount: 5200, favoritesCount: 1900, isVipEnabled: false, pricing: 'Paid', reviews: [], status: 'approved', origin: 'Global' },
  { id: 'scenario', name: 'Scenario', description: '生成一致性极佳的游戏美术资产。', category: 'Gaming AI', tags: ['Assets'], url: 'https://scenario.com', imageUrl: 'https://picsum.photos/seed/sce/400/250', rating: 4.9, reviewCount: 850, clickCount: 12000, favoritesCount: 5200, isVipEnabled: false, pricing: 'Paid', reviews: [], status: 'approved', origin: 'Global' },
  { id: 'unity-muse', name: 'Unity Muse', description: 'Unity 官方出品的 AI 提效全家桶。', category: 'Gaming AI', tags: ['Unity'], url: 'https://unity.com/muse', imageUrl: 'https://picsum.photos/seed/unity/400/250', rating: 4.85, reviewCount: 1500, clickCount: 52000, favoritesCount: 22000, isVipEnabled: false, pricing: 'Paid', reviews: [], status: 'approved', origin: 'Global' },
  { id: 'fuxi', name: '网易伏羲', description: '国内最顶尖的游戏 AI 实验室。', category: 'Gaming AI', tags: ['China'], url: 'https://fuxi.163.com', imageUrl: 'https://picsum.photos/seed/fuxi/400/250', rating: 4.96, reviewCount: 5400, clickCount: 210000, favoritesCount: 85000, isVipEnabled: false, pricing: 'Paid', reviews: [], status: 'approved', origin: 'China' },
  { id: 'tg-ai', name: '腾讯游戏 AI Lab', description: '绝悟等顶级 AI 技术的诞生地。', category: 'Gaming AI', tags: ['China'], url: 'https://ailab.tencent.com', imageUrl: 'https://picsum.photos/seed/tgai/400/250', rating: 4.98, reviewCount: 3200, clickCount: 180000, favoritesCount: 72000, isVipEnabled: false, pricing: 'Paid', reviews: [], status: 'approved', origin: 'China' },
  { id: 'convai', name: 'Convai', description: '为虚拟世界打造可实时对话的 NPC。', category: 'Gaming AI', tags: ['NPC'], url: 'https://convai.com', imageUrl: 'https://picsum.photos/seed/conv/400/250', rating: 4.82, reviewCount: 420, clickCount: 9200, favoritesCount: 3100, isVipEnabled: false, pricing: 'Paid', reviews: [], status: 'approved', origin: 'Global' },
  { id: 'promethean', name: 'Promethean AI', description: 'AI 辅助 3D 场景与关卡快速搭建。', category: 'Gaming AI', tags: ['3D'], url: 'https://prometheanai.com', imageUrl: 'https://picsum.photos/seed/pro/400/250', rating: 4.7, reviewCount: 150, clickCount: 4500, favoritesCount: 1200, isVipEnabled: false, pricing: 'Paid', reviews: [], status: 'approved', origin: 'Global' },
  { id: 'rosebud', name: 'Rosebud AI', description: '从文字指令直接生成游戏逻辑与世界。', category: 'Gaming AI', tags: ['Generator'], url: 'https://rosebud.ai', imageUrl: 'https://picsum.photos/seed/rose/400/250', rating: 4.65, reviewCount: 85, clickCount: 2100, favoritesCount: 650, isVipEnabled: false, pricing: 'Freemium', reviews: [], status: 'approved', origin: 'Global' },
  { id: 'mhy-ai', name: '米哈游 AI Lab', description: '二次元游戏顶尖 AI 技术中心。', category: 'Gaming AI', tags: ['China'], url: 'https://mihoyo.com', imageUrl: 'https://picsum.photos/seed/mhy/400/250', rating: 4.92, reviewCount: 5200, clickCount: 320000, favoritesCount: 110000, isVipEnabled: false, pricing: 'Paid', reviews: [], status: 'approved', origin: 'China' },

  // --- HARDWARE AI (9 tools) ---
  { id: 'r1', name: 'Rabbit R1', description: '引发全球关注的 LAM 驱动硬件。', category: 'Hardware AI', tags: ['Device'], url: 'https://rabbit.tech', imageUrl: 'https://picsum.photos/seed/r1/400/250', rating: 4.5, reviewCount: 8500, clickCount: 150000, favoritesCount: 42000, isVipEnabled: false, pricing: 'Paid', reviews: [], status: 'approved', origin: 'Global' },
  { id: 'humane', name: 'Humane AI Pin', description: '开创无屏、佩戴式交互新纪元。', category: 'Hardware AI', tags: ['Wearable'], url: 'https://humane.com', imageUrl: 'https://picsum.photos/seed/hmn/400/250', rating: 4.2, reviewCount: 5200, clickCount: 92000, favoritesCount: 31000, isVipEnabled: false, pricing: 'Paid', reviews: [], status: 'approved', origin: 'Global' },
  { id: 'xiaodu', name: '小度添添 AI', description: '国产智能屏与音箱的领军者。', category: 'Hardware AI', tags: ['China'], url: 'https://xiaodu.baidu.com', imageUrl: 'https://picsum.photos/seed/xd/400/250', rating: 4.8, reviewCount: 500000, clickCount: 15000000, favoritesCount: 3500000, isVipEnabled: false, pricing: 'Paid', reviews: [], status: 'approved', origin: 'China' },
  { id: 'xiaoai', name: '小爱同学', description: '小米全屋智能的 AI 大脑。', category: 'Hardware AI', tags: ['China'], url: 'https://xiaoai.mi.com', imageUrl: 'https://picsum.photos/seed/xai/400/250', rating: 4.85, reviewCount: 850000, clickCount: 25000000, favoritesCount: 6200000, isVipEnabled: false, pricing: 'Paid', reviews: [], status: 'approved', origin: 'China' },
  { id: 'air-glass', name: 'OPPO Air Glass', description: '国产轻量化 AI 辅助现实眼镜。', category: 'Hardware AI', tags: ['China'], url: 'https://oppo.com', imageUrl: 'https://picsum.photos/seed/oppo/400/250', rating: 4.7, reviewCount: 3100, clickCount: 45000, favoritesCount: 12000, isVipEnabled: false, pricing: 'Paid', reviews: [], status: 'approved', origin: 'China' },
  { id: 'rayban-meta', name: 'Ray-Ban Meta', description: '史上最实用的 AI 潮流眼镜。', category: 'Hardware AI', tags: ['Fashion'], url: 'https://meta.com/smart-glasses', imageUrl: 'https://picsum.photos/seed/rayban/400/250', rating: 4.9, reviewCount: 12000, clickCount: 250000, favoritesCount: 95000, isVipEnabled: false, pricing: 'Paid', reviews: [], status: 'approved', origin: 'Global' },
  { id: 'hw-vision', name: '华为 Vision Glass', description: '国产顶级移动巨幕与 AI 视觉。', category: 'Hardware AI', tags: ['China'], url: 'https://huawei.com', imageUrl: 'https://picsum.photos/seed/hwv/400/250', rating: 4.75, reviewCount: 5200, clickCount: 88000, favoritesCount: 31000, isVipEnabled: false, pricing: 'Paid', reviews: [], status: 'approved', origin: 'China' },
  { id: 'xp-ai', name: '小鹏 XGPT 智能座舱', description: '国产车载 AI 交互的标杆。', category: 'Hardware AI', tags: ['China'], url: 'https://xiaopeng.com', imageUrl: 'https://picsum.photos/seed/xp/400/250', rating: 4.94, reviewCount: 25000, clickCount: 450000, favoritesCount: 180000, isVipEnabled: false, pricing: 'Paid', reviews: [], status: 'approved', origin: 'China' },
  { id: 'li-ai', name: '理想同学 (Mind GPT)', description: '理想汽车自研多模态空间 AI。', category: 'Hardware AI', tags: ['China'], url: 'https://lixiang.com', imageUrl: 'https://picsum.photos/seed/li/400/250', rating: 4.96, reviewCount: 31000, clickCount: 520000, favoritesCount: 210000, isVipEnabled: false, pricing: 'Paid', reviews: [], status: 'approved', origin: 'China' },

  // --- ENTERPRISE AI (9 tools) ---
  { id: 'copilot-365', name: 'Microsoft 365 Copilot', description: 'Office 全家桶的终极办公伴侣。', category: 'Enterprise AI', tags: ['MS'], url: 'https://microsoft.com', imageUrl: 'https://picsum.photos/seed/msc/400/250', rating: 4.9, reviewCount: 85000, clickCount: 5000000, favoritesCount: 1800000, isVipEnabled: false, pricing: 'Paid', reviews: [], status: 'approved', origin: 'Global' },
  { id: 'workspace-ai', name: 'Google Workspace AI', description: 'Google 文档与邮件的 AI 赋能。', category: 'Enterprise AI', tags: ['Google'], url: 'https://workspace.google.com', imageUrl: 'https://picsum.photos/seed/gwa/400/250', rating: 4.85, reviewCount: 52000, clickCount: 2500000, favoritesCount: 950000, isVipEnabled: false, pricing: 'Paid', reviews: [], status: 'approved', origin: 'Global' },
  { id: 'ding-ai', name: '钉钉 AI 助理', description: '国产最强办公软件，覆盖 700 种技能。', category: 'Enterprise AI', tags: ['China'], url: 'https://dingtalk.com', imageUrl: 'https://picsum.photos/seed/ding/400/250', rating: 4.92, reviewCount: 250000, clickCount: 12000000, favoritesCount: 3500000, isVipEnabled: false, pricing: 'Freemium', reviews: [], status: 'approved', origin: 'China' },
  { id: 'fs-ai', name: '飞书智能伙伴', description: '协同办公标杆，极其好用的国产 AI。', category: 'Enterprise AI', tags: ['China'], url: 'https://feishu.cn', imageUrl: 'https://picsum.photos/seed/fs/400/250', rating: 4.96, reviewCount: 120000, clickCount: 6500000, favoritesCount: 2100000, isVipEnabled: false, pricing: 'Freemium', reviews: [], status: 'approved', origin: 'China' },
  { id: 'einstein', name: 'Salesforce Einstein', description: '全球 CRM 领军者的核心智能引擎。', category: 'Enterprise AI', tags: ['CRM'], url: 'https://salesforce.com', imageUrl: 'https://picsum.photos/seed/sf/400/250', rating: 4.82, reviewCount: 15000, clickCount: 850000, favoritesCount: 220000, isVipEnabled: false, pricing: 'Paid', reviews: [], status: 'approved', origin: 'Global' },
  { id: 'servicenow-ai', name: 'ServiceNow Generative AI', description: 'ITSM 领域的生成式 AI 专家。', category: 'Enterprise AI', tags: ['IT'], url: 'https://servicenow.com', imageUrl: 'https://picsum.photos/seed/sn/400/250', rating: 4.75, reviewCount: 3100, clickCount: 42000, favoritesCount: 15000, isVipEnabled: false, pricing: 'Paid', reviews: [], status: 'approved', origin: 'Global' },
  { id: 'pangu', name: '华为盘古大模型', description: '国产行业垂直（矿山、政务）大模型。', category: 'Enterprise AI', tags: ['China'], url: 'https://huaweicloud.com', imageUrl: 'https://picsum.photos/seed/hwp/400/250', rating: 4.94, reviewCount: 5200, clickCount: 120000, favoritesCount: 45000, isVipEnabled: false, pricing: 'Paid', reviews: [], status: 'approved', origin: 'China' },
  { id: 'nova', name: '商汤商量 (SenseNova)', description: '国产专业企业级大模型体系。', category: 'Enterprise AI', tags: ['China'], url: 'https://sensetime.com', imageUrl: 'https://picsum.photos/seed/ss/400/250', rating: 4.8, reviewCount: 2100, clickCount: 85000, favoritesCount: 31000, isVipEnabled: false, pricing: 'Paid', reviews: [], status: 'approved', origin: 'China' },
  { id: 'joule', name: 'SAP Joule', description: '全球 ERP 巨头的智能副驾驶。', category: 'Enterprise AI', tags: ['ERP'], url: 'https://sap.com', imageUrl: 'https://picsum.photos/seed/sap/400/250', rating: 4.7, reviewCount: 1500, clickCount: 32000, favoritesCount: 9500, isVipEnabled: false, pricing: 'Paid', reviews: [], status: 'approved', origin: 'Global' },

  // --- WEB GENERATION (9 tools) ---
  { id: 'v0', name: 'v0.dev', description: 'Vercel 出品，一键生成 React/Next.js 界面。', category: 'Web Generation', tags: ['NextJS'], url: 'https://v0.dev', imageUrl: 'https://picsum.photos/seed/v0/400/250', rating: 4.95, reviewCount: 8500, clickCount: 450000, favoritesCount: 180000, isVipEnabled: false, pricing: 'Freemium', reviews: [], status: 'approved', origin: 'Global' },
  { id: 'lovable', name: 'Lovable', description: '全栈级全自动 Web 应用开发。', category: 'Web Generation', tags: ['Fullstack'], url: 'https://lovable.dev', imageUrl: 'https://picsum.photos/seed/lovable/400/250', rating: 4.9, reviewCount: 1200, clickCount: 85000, favoritesCount: 32000, isVipEnabled: false, pricing: 'Freemium', reviews: [], status: 'approved', origin: 'Global' },
  { id: 'bolt', name: 'Bolt.new', description: '在浏览器中一键启动全栈应用。', category: 'Web Generation', tags: ['Fast'], url: 'https://bolt.new', imageUrl: 'https://picsum.photos/seed/bolt/400/250', rating: 4.92, reviewCount: 2100, clickCount: 120000, favoritesCount: 52000, isVipEnabled: false, pricing: 'Freemium', reviews: [], status: 'approved', origin: 'Global' },
  { id: 'wegic', name: 'Wegic AI', description: '国产 AI 建站专家，极致对白建站。', category: 'Web Generation', tags: ['China'], url: 'https://wegic.ai', imageUrl: 'https://picsum.photos/seed/wegic/400/250', rating: 4.85, reviewCount: 1500, clickCount: 42000, favoritesCount: 18000, isVipEnabled: false, pricing: 'Freemium', reviews: [], status: 'approved', origin: 'China' },
  { id: 'framer', name: 'Framer AI', description: '设计与搭建的一体化高端网页 AI。', category: 'Web Generation', tags: ['Design'], url: 'https://framer.com', imageUrl: 'https://picsum.photos/seed/framer/400/250', rating: 4.88, reviewCount: 12000, clickCount: 350000, favoritesCount: 120000, isVipEnabled: false, pricing: 'Freemium', reviews: [], status: 'approved', origin: 'Global' },
  { id: 'replit-ag', name: 'Replit Agent', description: '云端 IDE 的智能应用构建者。', category: 'Web Generation', tags: ['Agent'], url: 'https://replit.com', imageUrl: 'https://picsum.photos/seed/replit/400/250', rating: 4.9, reviewCount: 5200, clickCount: 150000, favoritesCount: 65000, isVipEnabled: false, pricing: 'Paid', reviews: [], status: 'approved', origin: 'Global' },
  { id: 'dora', name: 'Dora AI', description: '生成具有 3D 特效的高端动态网页。', category: 'Web Generation', tags: ['3D'], url: 'https://dora.run', imageUrl: 'https://picsum.photos/seed/dora/400/250', rating: 4.75, reviewCount: 3100, clickCount: 52000, favoritesCount: 19000, isVipEnabled: false, pricing: 'Freemium', reviews: [], status: 'approved', origin: 'Global' },
  { id: 'web10', name: '10Web AI', description: '一键克隆任何网站并发布。', category: 'Web Generation', tags: ['WordPress'], url: 'https://10web.io', imageUrl: 'https://picsum.photos/seed/10web/400/250', rating: 4.6, reviewCount: 2500, clickCount: 38000, favoritesCount: 12000, isVipEnabled: false, pricing: 'Paid', reviews: [], status: 'approved', origin: 'Global' },
  { id: 'coze-web', name: '扣子 Web 应用', description: '通过智能体一键发布为网页。', category: 'Web Generation', tags: ['China'], url: 'https://www.coze.cn', imageUrl: 'https://picsum.photos/seed/cozeweb/400/250', rating: 4.96, reviewCount: 15000, clickCount: 250000, favoritesCount: 110000, isVipEnabled: false, pricing: 'Free', reviews: [], status: 'approved', origin: 'China' },

  // --- PPT & SLIDES (9 tools) ---
  { id: 'gamma', name: 'Gamma', description: '目前全球体验最好的 AI 演示工具。', category: 'PPT & Slides', tags: ['SOTA'], url: 'https://gamma.app', imageUrl: 'https://picsum.photos/seed/gamma/400/250', rating: 4.95, reviewCount: 35000, clickCount: 1200000, favoritesCount: 580000, isVipEnabled: false, pricing: 'Freemium', reviews: [], status: 'approved', origin: 'Global' },
  { id: 'mindshow', name: 'MindShow', description: '国产良心，内容大纲转 PPT 专家。', category: 'PPT & Slides', tags: ['China'], url: 'https://mindshow.fun', imageUrl: 'https://picsum.photos/seed/mind/400/250', rating: 4.88, reviewCount: 12000, clickCount: 450000, favoritesCount: 180000, isVipEnabled: false, pricing: 'Freemium', reviews: [], status: 'approved', origin: 'China' },
  { id: 'chatppt', name: 'ChatPPT', description: '必优出品，深度集成 Office 的顶级 AI。', category: 'PPT & Slides', tags: ['China'], url: 'https://chatppt.com', imageUrl: 'https://picsum.photos/seed/chatppt/400/250', rating: 4.85, reviewCount: 18000, clickCount: 650000, favoritesCount: 220000, isVipEnabled: false, pricing: 'Freemium', reviews: [], status: 'approved', origin: 'China' },
  { id: 'aippt', name: 'AiPPT.cn', description: '国产大而全的智能 PPT 生成平台。', category: 'PPT & Slides', tags: ['China'], url: 'https://www.aippt.cn', imageUrl: 'https://picsum.photos/seed/aippt/400/250', rating: 4.78, reviewCount: 25000, clickCount: 520000, favoritesCount: 190000, isVipEnabled: false, pricing: 'Freemium', reviews: [], status: 'approved', origin: 'China' },
  { id: 'islide', name: 'iSlide AI', description: '老牌 PPT 插件的智能化全方位进化。', category: 'PPT & Slides', tags: ['China'], url: 'https://islide.cc', imageUrl: 'https://picsum.photos/seed/islide/400/250', rating: 4.82, reviewCount: 15000, clickCount: 380000, favoritesCount: 120000, isVipEnabled: false, pricing: 'Freemium', reviews: [], status: 'approved', origin: 'China' },
  { id: 'tome', name: 'Tome App', description: '以叙述为核心的精美 AI 幻灯片。', category: 'PPT & Slides', tags: ['Storytelling'], url: 'https://tome.app', imageUrl: 'https://picsum.photos/seed/tome/400/250', rating: 4.75, reviewCount: 21000, clickCount: 550000, favoritesCount: 150000, isVipEnabled: false, pricing: 'Freemium', reviews: [], status: 'approved', origin: 'Global' },
  { id: 'canva-slides', name: 'Canva Magic Design', description: 'Canva 旗下的全能设计转 PPT。', category: 'PPT & Slides', tags: ['Graphic'], url: 'https://canva.com', imageUrl: 'https://picsum.photos/seed/canva/400/250', rating: 4.9, reviewCount: 150000, clickCount: 2500000, favoritesCount: 850000, isVipEnabled: false, pricing: 'Freemium', reviews: [], status: 'approved', origin: 'Global' },
  { id: 'beautifulai', name: 'Beautiful.ai', description: '通过智能模板确保每一张 PPT 都精美。', category: 'PPT & Slides', tags: ['Template'], url: 'https://beautiful.ai', imageUrl: 'https://picsum.photos/seed/beautiful/400/250', rating: 4.65, reviewCount: 5400, clickCount: 120000, favoritesCount: 42000, isVipEnabled: false, pricing: 'Paid', reviews: [], status: 'approved', origin: 'Global' },
  { id: 'slidesai', name: 'SlidesAI.io', description: 'Google Slides 的首选 AI 插件。', category: 'PPT & Slides', tags: ['Plugin'], url: 'https://slidesai.io', imageUrl: 'https://picsum.photos/seed/slidesai/400/250', rating: 4.5, reviewCount: 3200, clickCount: 88000, favoritesCount: 25000, isVipEnabled: false, pricing: 'Freemium', reviews: [], status: 'approved', origin: 'Global' },

  // --- EXCEL & DATA (9 tools) ---
  { id: 'sheetai', name: 'SheetAI', description: '让 AI 帮你处理所有 Google Sheets 逻辑。', category: 'Excel & Data', tags: ['SaaS'], url: 'https://sheetai.app', imageUrl: 'https://picsum.photos/seed/sheet/400/250', rating: 4.78, reviewCount: 1200, clickCount: 45000, favoritesCount: 18000, isVipEnabled: false, pricing: 'Paid', reviews: [], status: 'approved', origin: 'Global' },
  { id: 'chatexcel', name: 'ChatExcel', description: '对话式操作表格，北大团队国产之光。', category: 'Excel & Data', tags: ['China'], url: 'https://chatexcel.com', imageUrl: 'https://picsum.photos/seed/ctx/400/250', rating: 4.92, reviewCount: 8500, clickCount: 150000, favoritesCount: 62000, isVipEnabled: false, pricing: 'Free', reviews: [], status: 'approved', origin: 'China' },
  { id: 'wps-excel', name: 'WPS AI 表格', description: '国产办公首选，极致适配中文办公习惯。', category: 'Excel & Data', tags: ['China'], url: 'https://ai.wps.cn', imageUrl: 'https://picsum.photos/seed/wpsexcel/400/250', rating: 4.88, reviewCount: 35000, clickCount: 950000, favoritesCount: 380000, isVipEnabled: false, pricing: 'Freemium', reviews: [], status: 'approved', origin: 'China' },
  { id: 'rows', name: 'Rows AI', description: '自带 AI 与 API 集成的新一代智能表格。', category: 'Excel & Data', tags: ['Integration'], url: 'https://rows.com', imageUrl: 'https://picsum.photos/seed/rows/400/250', rating: 4.75, reviewCount: 3200, clickCount: 52000, favoritesCount: 21000, isVipEnabled: false, pricing: 'Freemium', reviews: [], status: 'approved', origin: 'Global' },
  { id: 'fbot', name: 'Formula Bot', description: 'Excel 公式生成器的佼佼者。', category: 'Excel & Data', tags: ['Utility'], url: 'https://formulabot.com', imageUrl: 'https://picsum.photos/seed/fbot/400/250', rating: 4.82, reviewCount: 5400, clickCount: 88000, favoritesCount: 31000, isVipEnabled: false, pricing: 'Freemium', reviews: [], status: 'approved', origin: 'Global' },
  { id: 'numerous', name: 'Numerous.ai', description: '将 AI 注入每一格表格，批量任务专家。', category: 'Excel & Data', tags: ['Batch'], url: 'https://numerous.ai', imageUrl: 'https://picsum.photos/seed/numerous/400/250', rating: 4.65, reviewCount: 2100, clickCount: 42000, favoritesCount: 15000, isVipEnabled: false, pricing: 'Paid', reviews: [], status: 'approved', origin: 'Global' },
  { id: 'julius', name: 'Julius AI', description: '你的私人数据分析官，一键出图表。', category: 'Excel & Data', tags: ['Analysis'], url: 'https://julius.ai', imageUrl: 'https://picsum.photos/seed/julius/400/250', rating: 4.9, reviewCount: 4200, clickCount: 120000, favoritesCount: 54000, isVipEnabled: false, pricing: 'Freemium', reviews: [], status: 'approved', origin: 'Global' },
  { id: 'airtable', name: 'Airtable AI', description: '在低代码平台中深度整合生成式 AI。', category: 'Excel & Data', tags: ['LowCode'], url: 'https://airtable.com', imageUrl: 'https://picsum.photos/seed/airtable/400/250', rating: 4.85, reviewCount: 15000, clickCount: 350000, favoritesCount: 120000, isVipEnabled: false, pricing: 'Freemium', reviews: [], status: 'approved', origin: 'Global' },
  { id: 'gptexcel', name: 'GPTExcel', description: '简单快捷的 Excel & Sheets 公式助手。', category: 'Excel & Data', tags: ['Simple'], url: 'https://gptexcel.uk', imageUrl: 'https://picsum.photos/seed/gptexcel/400/250', rating: 4.5, reviewCount: 1800, clickCount: 25000, favoritesCount: 9200, isVipEnabled: false, pricing: 'Freemium', reviews: [], status: 'approved', origin: 'Global' },

  // --- DOCUMENT AI (9 tools) ---
  { id: 'jasper-doc', name: 'Jasper', description: '企业级内容营销与长文写作首选。', category: 'Document AI', tags: ['Enterprise'], url: 'https://jasper.ai', imageUrl: 'https://picsum.photos/seed/jasperdoc/400/250', rating: 4.92, reviewCount: 25000, clickCount: 850000, favoritesCount: 320000, isVipEnabled: false, pricing: 'Paid', reviews: [], status: 'approved', origin: 'Global' },
  { id: 'notion-doc', name: 'Notion AI (Docs)', description: '在笔记中直接润色、总结与续写。', category: 'Document AI', tags: ['Knowledge'], url: 'https://notion.so', imageUrl: 'https://picsum.photos/seed/notiondoc/400/250', rating: 4.9, reviewCount: 150000, clickCount: 5000000, favoritesCount: 2500000, isVipEnabled: false, pricing: 'Freemium', reviews: [], status: 'approved', origin: 'Global' },
  { id: 'wps-doc', name: 'WPS AI 文字', description: '最懂国产公文与职场报告的 AI。', category: 'Document AI', tags: ['China'], url: 'https://ai.wps.cn', imageUrl: 'https://picsum.photos/seed/wpsdoc/400/250', rating: 4.88, reviewCount: 42000, clickCount: 1500000, favoritesCount: 620000, isVipEnabled: false, pricing: 'Freemium', reviews: [], status: 'approved', origin: 'China' },
  { id: 'effie', name: 'Effie', description: '国产沉浸式写作，集成思想导图。', category: 'Document AI', tags: ['China'], url: 'https://effie.co', imageUrl: 'https://picsum.photos/seed/effie/400/250', rating: 4.82, reviewCount: 8500, clickCount: 110000, favoritesCount: 45000, isVipEnabled: false, pricing: 'Freemium', reviews: [], status: 'approved', origin: 'China' },
  { id: 'copy', name: 'Copy.ai', description: '全能营销文案生成引擎。', category: 'Document AI', tags: ['Marketing'], url: 'https://copy.ai', imageUrl: 'https://picsum.photos/seed/copy/400/250', rating: 4.8, reviewCount: 18000, clickCount: 450000, favoritesCount: 150000, isVipEnabled: false, pricing: 'Freemium', reviews: [], status: 'approved', origin: 'Global' },
  { id: 'grammarly-doc', name: 'Grammarly AI', description: '英文专业纠错与风格优化的基石。', category: 'Document AI', tags: ['Standard'], url: 'https://grammarly.com', imageUrl: 'https://picsum.photos/seed/grammarly/400/250', rating: 4.95, reviewCount: 250000, clickCount: 10000000, favoritesCount: 4500000, isVipEnabled: false, pricing: 'Freemium', reviews: [], status: 'approved', origin: 'Global' },
  { id: 'rytr', name: 'Rytr', description: '轻便、高性价比的写作辅助。', category: 'Document AI', tags: ['Simple'], url: 'https://rytr.me', imageUrl: 'https://picsum.photos/seed/rytr/400/250', rating: 4.65, reviewCount: 12000, clickCount: 180000, favoritesCount: 65000, isVipEnabled: false, pricing: 'Freemium', reviews: [], status: 'approved', origin: 'Global' },
  { id: 'writesonic-doc', name: 'Writesonic', description: 'SEO 友好型长文创作平台。', category: 'Document AI', tags: ['SEO'], url: 'https://writesonic.com', imageUrl: 'https://picsum.photos/seed/writesonic/400/250', rating: 4.78, reviewCount: 15000, clickCount: 220000, favoritesCount: 85000, isVipEnabled: false, pricing: 'Freemium', reviews: [], status: 'approved', origin: 'Global' },
  { id: 'zhibiao', name: '织表 (Zhibiao)', description: '国内创新的结构化文档处理。', category: 'Document AI', tags: ['China'], url: 'https://zhibiao.ai', imageUrl: 'https://picsum.photos/seed/zhibiao/400/250', rating: 4.5, reviewCount: 1200, clickCount: 25000, favoritesCount: 8200, isVipEnabled: false, pricing: 'Freemium', reviews: [], status: 'approved', origin: 'China' },

  // --- TASK AGENTS (9 tools) ---
  { id: 'coze', name: '扣子 (Coze.cn)', description: '字节跳动出品，国产 Agent 平台的天花板。', category: 'Task Agents', tags: ['China'], url: 'https://www.coze.cn', imageUrl: 'https://picsum.photos/seed/cozecn/400/250', rating: 4.98, reviewCount: 52000, clickCount: 1500000, favoritesCount: 820000, isVipEnabled: false, pricing: 'Free', reviews: [], status: 'approved', origin: 'China' },
  { id: 'zapier', name: 'Zapier Central', description: '赋予 AI 调度 6000+ 应用的能力。', category: 'Task Agents', tags: ['Automation'], url: 'https://zapier.com/central', imageUrl: 'https://picsum.photos/seed/zapier/400/250', rating: 4.9, reviewCount: 8500, clickCount: 120000, favoritesCount: 52000, isVipEnabled: false, pricing: 'Paid', reviews: [], status: 'approved', origin: 'Global' },
  { id: 'agpt', name: 'AutoGPT', description: '自主型 Agent 的鼻祖与标杆。', category: 'Task Agents', tags: ['OpenSource'], url: 'https://agpt.co', imageUrl: 'https://picsum.photos/seed/agpt/400/250', rating: 4.75, reviewCount: 15000, clickCount: 450000, favoritesCount: 180000, isVipEnabled: false, pricing: 'Free', reviews: [], status: 'approved', origin: 'Global' },
  { id: 'bd-ag', name: '百度智能体 (AgentBuilder)', description: '百度文心生态下的海量智能体库。', category: 'Task Agents', tags: ['China'], url: 'https://mbd.baidu.com/ma/agent/builder', imageUrl: 'https://picsum.photos/seed/bdag/400/250', rating: 4.8, reviewCount: 25000, clickCount: 850000, favoritesCount: 320000, isVipEnabled: false, pricing: 'Free', reviews: [], status: 'approved', origin: 'China' },
  { id: 'dify-ag', name: 'Dify Agent', description: '最受国产开发者欢迎的 Agent 搭建平台。', category: 'Task Agents', tags: ['China'], url: 'https://dify.ai', imageUrl: 'https://picsum.photos/seed/difyag/400/250', rating: 4.92, reviewCount: 12000, clickCount: 180000, favoritesCount: 65000, isVipEnabled: false, pricing: 'Freemium', reviews: [], status: 'approved', origin: 'China' },
  { id: 'lindy', name: 'Lindy.ai', description: '你的 AI 员工，自动处理日程与杂事。', category: 'Task Agents', tags: ['Assistant'], url: 'https://lindy.ai', imageUrl: 'https://picsum.photos/seed/lindy/400/250', rating: 4.88, reviewCount: 2100, clickCount: 52000, favoritesCount: 19000, isVipEnabled: false, pricing: 'Paid', reviews: [], status: 'approved', origin: 'Global' },
  { id: 'multion', name: 'MultiOn', description: '能在浏览器中真实操作网页的 Agent。', category: 'Task Agents', tags: ['Browsing'], url: 'https://multion.ai', imageUrl: 'https://picsum.photos/seed/multion/400/250', rating: 4.9, reviewCount: 1500, clickCount: 42000, favoritesCount: 15000, isVipEnabled: false, pricing: 'Paid', reviews: [], status: 'approved', origin: 'Global' },
  { id: 'agentgpt', name: 'AgentGPT', description: '在浏览器中直接部署并运行自主智能体。', category: 'Task Agents', tags: ['NoCode'], url: 'https://agentgpt.reworkd.ai', imageUrl: 'https://picsum.photos/seed/agentgpt/400/250', rating: 4.65, reviewCount: 12000, clickCount: 220000, favoritesCount: 85000, isVipEnabled: false, pricing: 'Freemium', reviews: [], status: 'approved', origin: 'Global' },
  { id: 'hyperwrite', name: 'HyperWrite Personal', description: '学习你的工作习惯并自动化任务。', category: 'Task Agents', tags: ['Personal'], url: 'https://hyperwriteai.com', imageUrl: 'https://picsum.photos/seed/hyper/400/250', rating: 4.72, reviewCount: 3100, clickCount: 48000, favoritesCount: 12000, isVipEnabled: false, pricing: 'Freemium', reviews: [], status: 'approved', origin: 'Global' },
];
